VirtoCommerce/vc-platform

PLATFORM/VirtoCommerce.Platform.Data/Infrastructure/Interceptors/GuidCombiPrimaryKeyGeneratorInterceptor.cs
PLATFORM/VirtoCommerce.Platform.Data/VirtoCommerce.Platform.Data.csproj

GuidCombiPrimaryKeyGeneratorInterceptor -  Primary key data type #123

GuidCombiPrimaryKeyGeneratorInterceptor -  Primary key data type #123

---

PLATFORM/Modules/Cart/VirtoCommerce.CartModule.Data/Converters/ShoppingCartConverter.cs

Encountered null reference exception when Currency property is null

Remove redundant ToString on cart.Currency

---

VirtoCommerce.Platform.Data.Azure/AzureBlobProvider.cs

Leverage Browser Caching - 7days 
Setting Cache-Control on Azure Blobs can help reduce bandwidth and improve the performance by preventing consumers from having to continuously download resources. 
More Info:
https://developers.google.com/speed/docs/insights/LeverageBrowserCaching
https://azure.microsoft.com/en-us/resources/samples/storage-blobs-powershell-cache-control/

Leverage Browser Caching - 7days

---

VirtoCommerce.Platform.Web/Content/themes/main/css/base-modules.css
VirtoCommerce.Platform.Web/Localizations/en.VirtoCommerce.Platform.json
VirtoCommerce.Platform.Web/Scripts/app/app.js
VirtoCommerce.Platform.Web/Scripts/app/navigation/menu/mainMenu.js
VirtoCommerce.Platform.Web/Scripts/app/navigation/menu/mainMenu.tpl.html
VirtoCommerce.Platform.Web/Scripts/app/pushNotifications/pushNotifications.js

BUG: Wrong sorting
BUG: ui-sortable not working with ng-model

Added minimal functionality for customizable menu

---

VirtoCommerce.Platform.Data.Security/SecurityService.cs

SecurityService methods are marked as virtual

SecurityService virtual methods

---

VirtoCommerce.Platform.Web/Startup.cs

Changed the CacheManager  initialization sequence to ensure the configuration is loaded from web.config if 'platformCache' exists.

Fixed CacheManager initialization

---

VirtoCommerce.Platform.Core.Web/Common/HostingEnvironmentPathMapper.cs
VirtoCommerce.Platform.Core.Web/VirtoCommerce.Platform.Core.Web.csproj
VirtoCommerce.Platform.Core/Common/IPathMapper.cs
VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj
VirtoCommerce.Platform.Data/Common/ConnectionStringHelper.cs
VirtoCommerce.Platform.Data/VirtoCommerce.Platform.Data.csproj
VirtoCommerce.Platform.Web/Startup.cs

Make Startup independent of System.Web, so it can be used in integration testing.
Allow injection of connection strings through environment variables to support release management.

Make Startup independent of System.Web, so it can be used in integration testing.

---

VirtoCommerce.Platform.Web/Content/themes/main/css/main.css
VirtoCommerce.Platform.Web/Scripts/app/modularity/dialogs/moduleAction-dialog.tpl.html

fix(moduleWizard):fixed popup size

---

VirtoCommerce.Platform.Data/Notifications/NotificationManager.cs
VirtoCommerce.Platform.Web/Scripts/app/notifications/blades/notifications-journal.tpl.html

Sent date was not displaying anymore and I removed the Order By "SentDate" since it should always be ordered by CreatedDate DESC by default.

Fix notifications display

---

CommonAssemblyInfo.cs
VirtoCommerce.Platform.Core.Web/VirtoCommerce.Platform.Core.Web.nuspec
VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.nuspec
VirtoCommerce.Platform.Data.Azure/VirtoCommerce.Platform.Data.Azure.nuspec
VirtoCommerce.Platform.Data.Notifications/VirtoCommerce.Platform.Data.Notifications.nuspec
VirtoCommerce.Platform.Data.Security/VirtoCommerce.Platform.Data.Security.nuspec
VirtoCommerce.Platform.Data.Serialization/VirtoCommerce.Platform.Data.Serialization.nuspec
VirtoCommerce.Platform.Data/VirtoCommerce.Platform.Data.nuspec
VirtoCommerce.Platform.Web/Startup.cs
VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
VirtoCommerce.Platform.Web/Web.config
VirtoCommerce.Platform.Web/packages.config

SignalR and Cache use Redis to distribute messages across Virto Commerce application that is deployed on several separate IIS instances.

#878 SignarR and platform scaleout issue

---

VirtoCommerce.Platform.Web/Scripts/common/angular-scroll-complete.js
VirtoCommerce.Platform.Web/Scripts/common/directives/angular-scroll-complete.js
VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

1254 Added angular-scroll-complete.js with a new directive

---

VirtoCommerce.Platform.Data/Repositories/PlatformRepository.cs

Extend PlatformRepository with additional constructor according to issue #1258

Extend PlatformRepository with additional constructor

---

VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

Reveal whether account exists

---

VirtoCommerce.Platform.Core/Security/UserSearchRequest.cs
VirtoCommerce.Platform.Data.Security/SecurityService.cs

Add ability to find extended users by multiple ids.

Find extended users by ids.

---

VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

Reset password notification should appear in notifications history

---

VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

en-US culture (default) should be used for Reset password template resolving

---

VirtoCommerce.Platform.Core/Security/AuthentificationOptions.cs
VirtoCommerce.Platform.Data.Security/Identity/ApplicationUserManager.cs
VirtoCommerce.Platform.Web/App_Start/OwinConfig.cs
VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
VirtoCommerce.Platform.Web/Startup.cs
VirtoCommerce.Platform.Web/Web.config

Added ability to specify authentication options in web.config

---

VirtoCommerce.Platform.Web/Content/themes/main/css/main.css

Fix errors style in log

---

PULL_REQUEST_TEMPLATE.md

Need to complete [community profile](https://github.com/VirtoCommerce/vc-platform/community)

Create PR template

---

VirtoCommerce.Platform.Web/Scripts/common/directives/genericValueInput.tpl.html

Datetime input required fix

---

VirtoCommerce.Platform.Core/Security/ISecurityService.cs
VirtoCommerce.Platform.Data.Security/SecurityService.cs
VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
VirtoCommerce.Platform.Web/Localizations/en.VirtoCommerce.Platform.json
VirtoCommerce.Platform.Web/Model/Security/ResetPasswordInfo.cs
VirtoCommerce.Platform.Web/Model/Security/ResetPasswordTokenInfo.cs
VirtoCommerce.Platform.Web/Scripts/app/security/dialogs/resetPasswordDialog.tpl.html
VirtoCommerce.Platform.Web/Scripts/app/security/security.js
VirtoCommerce.Platform.Web/Scripts/app/security/services/auth.js
VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

Added API for password reset token validation

---

VirtoCommerce.Platform.Tests/Events/EventSupressorTests.cs
VirtoCommerce.Platform.Tests/VirtoCommerce.Platform.Tests.csproj

Initial issue #1392 solved by @tatarincev. Added some unit tests for checking logic new 'EventSupressor' class 
Only unit-tests.
Nothing

Tests for EventSupressor

---

VirtoCommerce.Platform.Data/ExportImport/PlatformExportImportManager.cs

platform export class needs fixes

Catalog export failed on 404 error #161

---

VirtoCommerce.Platform.Web/Scripts/app/security/blades/account-api.js

JS error in console while new API Account blade opening
Need to remove all errors in console.
Added additional condition for blade.currentEntity object.

Account API blade fixed

---

VirtoCommerce.Platform.Web/Controllers/HomeController.cs
VirtoCommerce.Platform.Web/Model/PlatformSetting.cs
VirtoCommerce.Platform.Web/Startup.cs
VirtoCommerce.Platform.Web/Views/Shared/_Layout.cshtml

#1467 Allow to change shortcut icon for platform application 
Added "favicon" setting into "VirtoCommerce.Platform.UI.Customization", value is passed to Layout through ViewBag.

#1467 Allow to change shortcut icon for platform application

---

VirtoCommerce.Platform.Web/Controllers/HomeController.cs
VirtoCommerce.Platform.Web/Startup.cs

Changed default favicon path: "~/favicon.ico" => "favicon.ico"

Changed default icon path

---

VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
VirtoCommerce.Platform.Web/Scripts/app/exportImport/blades/import-main.js

- Logout user if he deletes himself
- Added client error handling for import/export

Features 1330 client error handling

---

VirtoCommerce.Platform.Web/Scripts/common/directives/dateTime-picker.js

Fixed timezone handling in datetimePicker by assigning proper value to ViewValue

1327 Fixed timezone handling in datetimePicker

---

VirtoCommerce.Platform.Data/DynamicProperties/DynamicPropertyService.cs

Changed comparer key for DynamicPropertyEntity

#1393: Fixed dynamic property rename error

---

VirtoCommerce.Platform.Web/Startup.cs

Error in browser console "Unexpected string in JSON at position 148" in allPackages.js
missed comma in json

fixed shortcut icon for platform application

---

.gitignore
VirtoCommerce.Platform.Core.Web/VirtoCommerce.Platform.Core.Web.csproj
VirtoCommerce.Platform.Core.Web/packages.config
VirtoCommerce.Platform.Tests/app.config
VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
VirtoCommerce.Platform.Web/Web.config
VirtoCommerce.Platform.Web/packages.config

Updated AspNet packaged to the latest versions (5.2.7)

#1520 Update Microsoft.AspNet.* libraries to latest 5.2.7 versions

---

VirtoCommerce.Platform.Web/Web.config

extend limited cookie permissions

fix Cannot download license file

---

VirtoCommerce.Platform.Data.Azure/AzureBlobProvider.cs

added TrimStart to azureBlobStorege Url Generator

fix Broken url in assets - catalog - SKU image

---

VirtoCommerce.Platform.Core.Web/Assets/BlobStorageMultipartStreamProvider.cs
VirtoCommerce.Platform.Data.Azure/AzureBlobProvider.cs

fix Incorrect upload Images in the assets with "spaces" in the name 

---

VirtoCommerce.Platform.Web/Scripts/app/security/services/auth.js

fix Login error not shown

---

VirtoCommerce.Platform.Data.Notifications/VirtoCommerce.Platform.Data.Notifications.csproj
VirtoCommerce.Platform.Data.Notifications/packages.config
VirtoCommerce.Platform.Tests/app.config
VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
VirtoCommerce.Platform.Web/packages.config

update versions of dependencies

fix Different versions of dependencies

---

VirtoCommerce.Platform.Data.Security/SecurityService.cs
VirtoCommerce.Platform.Data/Assets/AssetEntryService.cs
VirtoCommerce.Platform.Data/Notifications/NotificationManager.cs
VirtoCommerce.Platform.Web/Scripts/app/security/services/auth.js

Paged search ordering revision

---

VirtoCommerce.Platform.Web/Scripts/common/directives/chars-count.js

replace   `   char to  "   for IE 11

replacement "`" char

---

VirtoCommerce.Platform.Data.Notifications/VirtoCommerce.Platform.Data.Notifications.csproj
VirtoCommerce.Platform.Data.Notifications/app.config
VirtoCommerce.Platform.Data.Notifications/packages.config
VirtoCommerce.Platform.Data.Security/App.config
VirtoCommerce.Platform.Data.Security/VirtoCommerce.Platform.Data.Security.csproj
VirtoCommerce.Platform.Data.Security/packages.config
VirtoCommerce.Platform.Tests/app.config
VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
VirtoCommerce.Platform.Web/Web.config
VirtoCommerce.Platform.Web/packages.config

Updated Microsoft.Owin* packages to 4.0.0 versions to avoid type loading exception;
System.IdentityModel.* were updated to 5.2.1 accordingly;
Consolidated System.IdentityModel.* dependencies;

#1600: Library loading exception when AzureAd enabled

---

VirtoCommerce.Platform.Web/Web.config

Added "content:create" to LimitedCookiePermissions to allow upload themes.

#1577: Added "content:create" to LimitedCookiePermissions to allow upload themes.

---

VirtoCommerce.Module/tools/VirtoCommerce.Module.psm1

Support VS 2019 in Compress-Module script

---

VirtoCommerce.Platform.Data.Serialization/XmlExpressionSerializer.cs

1623: add critical section to _expressionSerializer.Deserialize usage

---

VirtoCommerce.Platform.Core/Common/ConfigurationHelper.cs
VirtoCommerce.Platform.Data/Settings/SettingManager.cs
VirtoCommerce.Platform.Tests/Settings/SettingsManagerTests.cs
VirtoCommerce.Platform.Tests/VirtoCommerce.Platform.Tests.csproj

This PR covers part of this issue: https://github.com/VirtoCommerce/vc-platform/issues/1002
ISettingsManager.GetValue() will check the following data sources:
1. Environment variables
2. AppSettings
3. Database

#1002 Check environment variables and appSettings before getting setting value from database

---

VirtoCommerce.Platform.Web/Scripts/app/app.js

VP-576: Fixed localization problems when auth token expires by passing localization request without authorization.

VP-576: Fixed localization problems when auth token expires by passing localization request without authorization.

---

src/VirtoCommerce.Platform.Web/Startup.cs

https://virtocommerce.atlassian.net/browse/VP-700

#vp700 AllowCombiningAuthorizeFilters fix

---

VirtoCommerce.Platform.Web/Controllers/Api/SettingController.cs
VirtoCommerce.Platform.Web/Converters/Settings/SettingConverter.cs
VirtoCommerce.Platform.Web/Model/Settings/Setting.cs

https://virtocommerce.atlassian.net/browse/VP-725

#VP-725 show runtime settings

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/wizards/newModule/module-wizard-progress-step.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settingGroup-list.js

https://virtocommerce.atlassian.net/browse/VP-750

#vp750 working on Edge

---

VirtoCommerce.Platform.Data/Settings/SettingExtensions.cs
VirtoCommerce.Platform.Data/Settings/SettingManager.cs

https://virtocommerce.atlassian.net/browse/VP-772

vp-772 save runtime settings

---

docs/deploy-from-precompiled-binaries-linux.md

fix linux description

---

build/Build.cs

Added optional parameter to sending pre-releases on github

vc-build Release -PreRelease

---

src/VirtoCommerce.Platform.Web/Controllers/Api/AssetEntryController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/AssetsController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/ChangeLogController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/DynamicPropertiesController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/ModulesController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/ProfilesController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SettingController.cs

Expose DynamicObjectProperty in swagger thru fake action.

ProducesResponseType attribute set for NoContent returning actions.

---

VirtoCommerce.Platform.Web/Scripts/app/systemInfo/blades/system-info.js
VirtoCommerce.Platform.Web/Scripts/app/systemInfo/blades/system-info.tpl.html

dowinload manifest.v2 copy plain text. change button titles

---

docs/create-new-module.md

https://virtocommerce.atlassian.net/browse/CCIT-88

Guide "How to create a new Dummy module" added

---

VirtoCommerce.Platform.Web/Scripts/app/security/security.js

FE: Additional HTTP code 400 for incorrect login or password is checking now.

---

VirtoCommerce.Platform.Web/App_Start/OwinConfig.cs
VirtoCommerce.Platform.Web/Web.config

add cors settings to web.config 
enable cors for platform

Vp 1126 add cors settings

---

src/VirtoCommerce.Platform.Security/Services/CustomUserManager.cs

fix for https://github.com/VirtoCommerce/vc-platform/issues/1749

fix saving user details changes

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/module-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/module-detail.tpl.html

for https://github.com/VirtoCommerce/vc-platform/issues/1745

fix display of dependencies

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_forms.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/dynamicProperty-detail.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/property-dictionary.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/genericValueInput.tpl.html

for https://github.com/VirtoCommerce/vc-module-catalog/issues/250

change flags for culture names

---

VirtoCommerce.Platform.Web/Content/themes/main/css/main.css
VirtoCommerce.Platform.Web/Content/themes/main/sass/modules/_base-modules.sass
VirtoCommerce.Platform.Web/Content/themes/main/sass/modules/_forms.sass
VirtoCommerce.Platform.Web/Scripts/app/dynamicProperties/blades/dynamicProperty-detail.tpl.html
VirtoCommerce.Platform.Web/Scripts/app/dynamicProperties/blades/property-dictionary.tpl.html
VirtoCommerce.Platform.Web/Scripts/common/directives/genericValueInput.tpl.html

for https://github.com/VirtoCommerce/vc-module-catalog/issues/250

update culture name labels

---

VirtoCommerce.Platform.Web/Scripts/app/dynamicProperties/blades/dynamicProperty-list.js
VirtoCommerce.Platform.Web/Scripts/app/dynamicProperties/blades/propertyValue-list.js
VirtoCommerce.Platform.Web/Scripts/app/dynamicProperties/resources/dynamicPropertiesApi.js

https://virtocommerce.atlassian.net/browse/VP-1161

VP-1161 Creating dynamic properties in Store

---

VirtoCommerce.Platform.Web/Modularity/ManifestModuleCatalog.cs
VirtoCommerce.Platform.Web/Web.config

Add server localization codes to web.config
Copy satellite localization assemblies from modules

dev 1634 Localization of custom modules is not working

---

VirtoCommerce.Platform.Web/Scripts/app/app.js

The decorator should call  callback function onAfterAddingFile  of the instance of the class FileUploader and not the prototype default callback.
it`s related to issue for vc-module-content
https://github.com/virtocommerce/vc-module-content/issues/26
https://github.com/virtocommerce/vc-module-content/issues/36

Fix decorator of FileUploader.prototype._onAfterAddingFile

---

src/VirtoCommerce.Platform.Web/Swagger/ArrayInQueryParametersFilter.cs
src/VirtoCommerce.Platform.Web/Swagger/SwaggerServiceCollectionExtensions.cs

See more: https://github.com/Azure/autorest/issues/3373.

The workaround for openapi3/autorest query parameters serialization

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-resetPassword.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/security.js

https://virtocommerce.atlassian.net/browse/VP-1276

#vp 1276 reset password link

---

src/VirtoCommerce.Platform.Web/web.config

With existing web.config, IIS blocks such requests with 405.

1778: Allow PUT and DELETE requests on IIS

---

build/Build.cs
build/CHANGELOG.md
build/_build.csproj

Updated Dependencies;
Fixed issue with Gitversion and Nuke.Common;

3.0.0-beta0008

---

src/VirtoCommerce.Platform.Web/appsettings.json

Replace SampleDataUrl with CDN Url (virtocommerce.azureedge.net) to improve download speed of the sample data.

Replace SampleDataUrl with CDN Url

---

VirtoCommerce.Platform.Web/Web.config

Replace SampleDataUrl with CDN Url (virtocommerce.azureedge.net) to improve download speed of the sample data.

vp-1472 Replace SampleDataUrl with CDN Url

---

VirtoCommerce.Platform.Web/Scripts/app/systemInfo/blades/system-info.tpl.html

VP-1556: Licence type mismatch

---

VirtoCommerce.Platform.Data.Notifications/SendGridEmailNotificationSendingGateway.cs
VirtoCommerce.Platform.Data/Notifications/DefaultSmtpEmailNotificationSendingGateway.cs
VirtoCommerce.Platform.Web/Startup.cs

Supported environment variables precedence for `DefaultSmtpEmailNotificationSendingGateway` and `SendGridEmailNotificationSendingGateway` settings.

VP-1699: Support env variables in email gateways settings

---

src/VirtoCommerce.Platform.Core/Domain/Entity.cs

VP-1838 sonar bug remove base

---

src/VirtoCommerce.Platform.Core/Extensions/StringExtensions.cs

VP-1839: Add comment for the empty catch.

VP-1839: Sonar bug empty catch

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settingGroup-list.tpl.html

VP-1808: Fix string to translate

VP-1808: No Localizaion on Search

---

build/Build.cs
build/CHANGELOG.md
build/_build.csproj

- Custom logger for DotnetTasks
- ValidateSwaggerSchema Target
- Support for Pull Request in SonarQubeStart Target
- An issue with dependencies filter at Compress Target
- An issue with packaging vc-build with 3rd party tools
- NUKE Execution Engine updated to 0.24.7
- GitVersion updated to 5.2.4
- Virtocommerce.Platform dependency changed from ProjectReference to PackageReference

3.0.0-beta0009

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settingGroup-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settingGroup-list.tpl.html

VP-1808: Translate setting names in js file

VP-1808: Fix Localizaion on Search

---

VirtoCommerce.Platform.Web/Scripts/common/directives/fallbackSrc.js

Fix IE-11 compatibility

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Common.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/exportImport.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/widgets/sampleDataImportWidget.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/widgets/sampleDataImportWidget.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settings-detail.js

Added widget to Platform\Setup settings that could run import;

VP-1949: Add Import sample data button to settings

---

src/VirtoCommerce.Platform.Web/appsettings.json

VP-1929: Set RequireUniqueEmail to true as default value

VP-1929: The platform allows to register a new user with existing email

---

docs/Migrate-module-from-the-Platform-2.0-to-3.0-version.md
docs/create-new-module.md
docs/extend-DB-model.md

Add guide: VC3.0 - How to create DB migration

---

src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

VP-1883 Add NuGet package that will build webpack on the first solution build

VP-1883 Add NuGet package to build webpack

---

VirtoCommerce.Platform.Data.Security/Converters/ApplicationUserConverter.cs

Add storeId to account patch

---

docs/connect-storefront-to-platform-v3.md

VP-2272: E2E Preparation

---

.github/workflows/main.yml

1. External contributors don't have access to CI results for details.
2. Experiment with using GitHub Actions instead of Jenkins.
Create a GitHub Actions CI pipeline with essential steps to verify Pull Requsts.
A new file with a pipeline has been implemented.
.github/workflows/main.yml
N/A

VP-2440: Add CI pipeline

---

.github/workflows/main.yml

Add swagger validation to the GitHub CI
Add changes to the CI
Build and publish an image to the GitHub packages. 
Validate the image
Publish image to the hub.docker.io for master and dev branches.
N/A

VP-2541: GitHub Actions for platform CI: Build and publish docker image 

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/modules-list.js

Not correct behavior when trying toggle modules bundles selection.
UI-Grid 4.0.1 which we using in VC2 (those code were migrated in VC3) we were needed implement selection of group tree ourselves, but in v 4.0.5 selection is implemented by UI-Grid https://github.com/angular-ui/ui-grid/pull/6167
Remove redundant behavior

VP-1681: Platform > Modules deselected when I select modules bundle and versa vers

---

.github/sonar-project.properties
.github/workflows/main.yml

Github Actions CI doesn't have SonarCloud analysis
Add an action with the analysis step

VP-2655: GitHub Actions for platform CI: SonarCloud integration

---

.github/workflows/delivery.yml
.github/workflows/main.yml

http://webstore-platform.dev.govirto.com/ doesn't work
Change the link to the correct dockerfile
Use https://raw.githubusercontent.com/VirtoCommerce/vc-docker/master/linux/platform/Dockerfile
instead of 
https://raw.githubusercontent.com/VirtoCommerce/jenkins-pipeline-scripts/master/resources/docker.core/linux/platform/Dockerfile

VP-3195: Update platfrom dockerfile source

---

docs/developer-guide/extending-commerce/creating-new-payment-method.md
docs/lessons/lesson3.md
docs/lessons/lesson4.md
docs/old-versions/vc113devguide/architecture/extending-and-using-logging-system.md
docs/old-versions/vc113devguide/architecture/long-running-tasks.md
docs/old-versions/vc113devguide/tutorials/add-new-module-to-virtocommerce-admin.md
docs/old-versions/vc113userguide/dashboard.md
docs/old-versions/vc113userguide/fulfillment/picklists.md
docs/old-versions/vc113userguide/merchandise-management/import.md
docs/old-versions/vc113userguide/settings/stores.md
docs/technical-case-studies/recommended-price.md

Incorrect character sequence вЂ“ replaced by - in md files

Fix incorrect dash

---

build/Build.cs
build/CHANGELOG.md
build/Directory.Build.Props

Parameters VersionTag and CustomTagSuffix were replaced with CustomVersionSuffix. 
If Directory.Build.Props has no VersionSuffix, then it will update with CustomVersionSuffix

vc-build 1.1.0

---

src/VirtoCommerce.Platform.Modules/Local/LocalStorageModuleCatalog.cs

In some cases (e.g. multiple instances sharing one probing folder) platform could be unable to start because of each instance is trying to write its version of file. Need to allow platform to start in case of versions are the same, only modification date differ. Still warnings about such facts would be logged.

VP-3719: Allow platofrm to start when cannot copy same version assembly

---

src/VirtoCommerce.Platform.Assets.AzureBlobStorage/AzureBlobOptions.cs
src/VirtoCommerce.Platform.Assets.AzureBlobStorage/AzureBlobProvider.cs
src/VirtoCommerce.Platform.Assets.AzureBlobStorage/VirtoCommerce.Platform.Assets.AzureBlobStorage.csproj

Resolve deprecated reference: https://virtocommerce.atlassian.net/browse/VP-3849

VP-3849: Replace deprecated package to Microsoft.Azure.Storage.Blob

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

https://virtocommerce.atlassian.net/browse/VP-3720

VP-3720: Enable creating user without password

---

src/VirtoCommerce.Platform.Assets.AzureBlobStorage/AzureBlobOptions.cs
src/VirtoCommerce.Platform.Assets.AzureBlobStorage/AzureBlobProvider.cs
src/VirtoCommerce.Platform.Assets.AzureBlobStorage/VirtoCommerce.Platform.Assets.AzureBlobStorage.csproj

Reverts VirtoCommerce/vc-platform#1957

Revert "VP-3849: Replace deprecated package to Microsoft.Azure.Storage.Blob"

---

.github/workflows/main.yml

CI fails on Swagger schema validation step
Switch Hangfire into the in-memory mode
In CI main.yaml:
- docker-compose hangfire parameter value set to “memory”
- docker-compose Timeout connection parameter value set to 300
- fixed build number sequence (checkout fetch-depth parameter value set 1)

VP-4142: Fix fails on swagger schema validation

---

.github/workflows/main.yml

Changed $GITHUB_REPOSITORY to $('${{ github.repository }}'.ToLower())

VP-4159: Fix run container step fail

---

src/VirtoCommerce.Platform.Core/Modularity/ExternalModuleCatalogOptions.cs

https://virtocommerce.atlassian.net/browse/VP-4219

VP-4219: Enable skipping default modules installation

---

build/Build.cs
build/CHANGELOG.md
build/Directory.Build.props
build/_build.csproj

- Directory.Build.props search
- Search of Web-projects
- Search of Tests Assemblies and Projects
- Swashbuckle.AspNetCore.Cli dependency resolving
- SonarQubeStart target for using it with SonarCloud

vc-build 1.3.7

---

src/VirtoCommerce.Platform.Assets.AzureBlobStorage/AzureBlobProvider.cs

https://virtocommerce.atlassian.net/browse/VP-2072
https://virtocommerce.atlassian.net/browse/VP-2077
Describe the technical details of the realization provided by you.

VP-2072/7 Fix: azure blob provider renaming feature

---

src/VirtoCommerce.Platform.Web/Controllers/Api/AssetsController.cs
src/VirtoCommerce.Platform.Web/Validators/BlobFolderValidator.cs
src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
src/VirtoCommerce.Platform.Web/wwwroot/js/app/assets/blades/asset-list.js
tests/VirtoCommerce.Platform.Tests/Validators/BlobFolderValidatorTests.cs
tests/VirtoCommerce.Platform.Tests/Validators/ValidatorTestsHelper.cs
tests/VirtoCommerce.Platform.Tests/VirtoCommerce.Platform.Tests.csproj

https://virtocommerce.atlassian.net/browse/VP-1975

VP-1975 Fix: add validation to folder create operation

---

src/VirtoCommerce.Platform.Web/Validators/BlobFolderValidator.cs

VP-1975: Fix regex in validator

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/assets/blades/asset-list.js

VP-1975 Feat: show text rules for asset create folder operation

---

src/VirtoCommerce.Platform.Assets.AzureBlobStorage/AzureBlobProvider.cs

https://virtocommerce.atlassian.net/browse/VP-2077

VP-2077: Fix remove specsymbols

---

src/VirtoCommerce.Platform.Web/Controllers/Api/AssetsController.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/assets/blades/asset-list.js

https://virtocommerce.atlassian.net/browse/VP-4566
https://virtocommerce.atlassian.net/browse/VP-1975

VP-4566: Change error contract for UI interceptor

---

.github/workflows/main.yml

Added additional params to Build Docker Image step

VP-4625: Update Workflow

---

docs/getting-started/connect-storefront-to-platform-v3.md

Provide correct symlink in documentation
https://virtocommerce.com/docs/latest/getting-started/connect-storefront-to-platform-v3/

VP-4364: Incorrect symlink

---

src/VirtoCommerce.Platform.Web/Views/Shared/_AppDependencies.cshtml
src/VirtoCommerce.Platform.Web/Views/Shared/_Layout.cshtml
src/VirtoCommerce.Platform.Web/wwwroot/js/app/app.js

Reverts VirtoCommerce/vc-platform#2032

Revert "VP-4971: Add mainApp as UI app entry point"

---

src/VirtoCommerce.Platform.Data/Extensions/ServiceCollectionExtensions.cs
src/VirtoCommerce.Platform.Hangfire/ApplicationBuilderExtensions.cs
src/VirtoCommerce.Platform.Hangfire/ServiceCollectionExtensions.cs
src/VirtoCommerce.Platform.Web/Startup.cs

VP-4857: Ensure Hangfire schema will be applied to storage AFTER platform database creation

---

src/VirtoCommerce.Platform.Web/Controllers/ExternalSignInController.cs

VP-5066: Fix AAD SSO: pass external user email to microsoft identity

---

src/VirtoCommerce.Platform.Core/Extensions/StringExtensions.cs
src/VirtoCommerce.Platform.Web/Controllers/ExternalSignInController.cs

Add email string validation method to StringExtensions.

VP-5066: Change external login email validation

---

src/VirtoCommerce.Platform.Core/Extensions/IQueryableExtensions.cs

Removed redundant OfType() and corresponding stuff.

VP-4946: Fix broken queries for extended entities

---

src/VirtoCommerce.Platform.Data/Extensions/ApplicationBuilderExtensions.cs

https://virtocommerce.atlassian.net/browse/VP-4321

VP-4321: Null user name not available

---

src/VirtoCommerce.Platform.Web/Licensing/License.cs

https://virtocommerce.atlassian.net/browse/VP-5355

VP-5355: Suppress RSA key error

---

src/VirtoCommerce.Platform.Web/Security/CustomUserManager.cs

VP-5334 Call ClearCache before publish event

---

src/VirtoCommerce.Platform.Web/Controllers/Api/LicensingController.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/licensing/license-detail.js

VP-5352: Fix vulnerability in LicensingController

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/assets/blades/asset-upload.js

Current implementation of the asset upload blade has two issues:
1. If you set accepted MIME type to `image/*` or to some specific image type, it only allows to upload PNG, JPG, GIF and BMP images. You won't be able to upload SVG images, even though they are images too.
2. Even if you specify some specific type (e.g. `image/svg+xml`), the blade will allow to upload just any image with allowed type. There is no way to allow uploading specific images, e.g. SVG images only.
1. We should add `svg+xml` to a list of allowed images;
2. Also, it would be nice to have a way to filter uploaded files by file type.
So, I did the following changes:
1. Added `svg+xml` to a list of allowed image types;
2. Added a new optional parameter for the blade - `filterCallback`, which should be a function …

HDOT-1745 Asset upload blade: allow uploading SVG images, add a way to define custom asset filters

---

src/VirtoCommerce.Platform.Web/Controllers/Api/PlatformExportImportController.cs

https://virtocommerce.atlassian.net/browse/VP-5353

VP-5353: Check localPath before processing

---

src/VirtoCommerce.Platform.Web/Controllers/Api/PlatformExportImportController.cs

Fix error on any manually running import in the platform

VP-5353: Fix error in import

---

build/Build.cs
build/Directory.Build.props

Fixed fails when project's dir is not a git repo

VP-5655: vc-build 1.4.18

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/de.VirtoCommerce.Common.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Common.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ru.VirtoCommerce.Common.json

VP-3570: Add lost localization

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/pushNotifications/resources/signalRHubProxy.js

Reverts VirtoCommerce/vc-platform#2094
Need to add an ability to switch off WebSockets using

Revert "VP-5861: Configure SignalR to use websockets and skip negotiation"

---

src/VirtoCommerce.Platform.Web/Startup.cs

https://virtocommerce.atlassian.net/browse/VP-6139

#VP-6147 move UseEndpoints after UseModules

---

src/VirtoCommerce.Platform.Core/PlatformConstants.cs
src/VirtoCommerce.Platform.Security/CustomUserClaimsPrincipalFactory.cs

VP-6222 Fix permission scope "Only for order responsible"
Add member id claim type

VP-6222: Add member id claim type

---

src/VirtoCommerce.Platform.Web/npm-shrinkwrap.json
src/VirtoCommerce.Platform.Web/package.json
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/includes/_constants.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass
src/VirtoCommerce.Platform.Web/wwwroot/src/js/vendor.js

VP-6364 Add icons to widgets inside Product blade
Add font-awesome version 5 package.

VP-6364: Add font awesome 5

---

build/Build.cs
build/CHANGELOG.md
build/Directory.Build.props
build/_build.csproj

- VCBUILD_DISABLE_RELEASE_APPROVEMENT environment variable to disable release approvement
- Updated Nuke.Common dependency
- github-release tool replaced by Octokit

VP-6452: vc-build 1.4.19

---

src/VirtoCommerce.Platform.Web/Views/Shared/_Layout.cshtml

For testing on QA
Need to revert after https://virtocommerce.atlassian.net/browse/VP-6379 tested.

VP-6379: Update _Layout.cshtml

---

build/Build.cs
build/CHANGELOG.md
build/Directory.Build.props
build/_build.csproj

- QuickRelease target works with themes now

VP-6426: vc-build 1.5.0

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/breadcrumbs/breadcrumbs.tpl.html

VP-6375 Change navigation (breadcrumbs) style for Catalog blades 
We have an extra level in breadcrumbs.
Because of the current style there are many misclicks and misunderstandings
Update breadcrumbs style.

VP-6375: Change breadcrumbs style

---

src/VirtoCommerce.Platform.Web/appsettings.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/assets/blades/asset-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/assets/blades/asset-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/assets/blades/asset-upload.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/dynamicProperty-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/dynamicProperty-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/property-dictionary.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/property-dictionary.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/module-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/modules-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/modules-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-api.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-roles-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-roles-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/oauthapps-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/oauthapps-detail.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/oauthapps-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/oauthapps-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-detail.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settings-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/common/blades/edit-array.js
src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/genericValueInput.tpl.html

VP-6366: Replace panel action icons

---

src/VirtoCommerce.Platform.Web/npm-shrinkwrap.json
src/VirtoCommerce.Platform.Web/package.json
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass

Update Font Awesome package version

VP-6648: Add icons to widgets inside Store settings blade

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/changeLog/widgets/operations-widget.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/blade/bladeContainer.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/widgets/accountApiWidget.tpl.html

Fix user blade UI issues
Add icons

VP-6764: Security section User list improvements

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-roles-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-roles-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-detail.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-list.js

VP-6766: Update assigned roles blades UI

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/uiScroll.js
src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/uiScroll.tpl.html

VP-6852 Set new pricelist assignments are only possible for the first 20 catalogs
Absent common component 
Add directive for dropdown infinite scroll

VP-6852: Add infinite scroll for catalog and priselist selectors

---

src/VirtoCommerce.Platform.Security/Caching/ApiKeyCacheRegion.cs

Jira: https://virtocommerce.atlassian.net/browse/VP-6877

VP-6877: Fix potential issues with caching

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/genericValueInput.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/metaform.js
src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/metaform.tpl.html

VP-7047: Add colSpan support to va-metaform; 
Add disabled and custom placeholder support to va-generic-value-input

VP-7047: Add colSpan support to va-metaform;

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/propertyValue-list.js

Fix wrong enabling SAVE button

VP-6933: Button SAVE active after open dynamic properties blade

---

src/VirtoCommerce.Platform.Core/PlatformConstants.cs
src/VirtoCommerce.Platform.Core/Security/Events/UserVerificationEmailEvent.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_forms.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/resources/accounts.js

Add permission for Verify Email switcher
Add Emeil verifivation event
Add switcher to ui and apply for permission

VP-6884: Verified status for an email address on the account blade

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.tpl.html

Check additional permission for emailConfirmed field when update user

VP-6888: Change verification status manually

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.tpl.html

Add localization for permission

VP-6888: add localization for permission

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/includes/_reset.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.tpl.html

Hide resend link when email changed and not saved

VP-7223: Disable resend link when email changed and not saved

---

src/VirtoCommerce.Platform.Core/ChangeLog/OperationLog.cs

https://virtocommerce.atlassian.net/browse/PT-201
The method override can be called in order to specify the operationType.

PT-201: Add override for FromChangedEntry to accept operationType

---

src/VirtoCommerce.Platform.Core/Security/ApplicationUserExtensions.cs

https://virtocommerce.atlassian.net/browse/PT-167

PT-332: modify DetectUserChanges method

---

src/VirtoCommerce.Platform.Core/Security/ApplicationUser.cs
src/VirtoCommerce.Platform.Security/Migrations/20210323075715_LastPasswordChangedDate.Designer.cs
src/VirtoCommerce.Platform.Security/Migrations/20210323075715_LastPasswordChangedDate.cs
src/VirtoCommerce.Platform.Security/Repositories/SecurityDbContext.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/Model/Security/UserDetail.cs
src/VirtoCommerce.Platform.Web/Security/CustomUserManager.cs

https://virtocommerce.atlassian.net/browse/PT-578

PT-578: Add property ApplicationUser.LastPasswordChangedDate

---

.github/workflows/e2e.yml
src/VirtoCommerce.Platform.Web/Telemetry/ServiceCollectionExtensions.cs
src/VirtoCommerce.Platform.Web/Telemetry/UserTelemetryInitializer.cs

https://virtocommerce.atlassian.net/browse/PT-372

PT-373 add user name to request telemetry

---

src/VirtoCommerce.Platform.Core/PlatformOptions.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/DiagnosticsController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/LicensingController.cs
src/VirtoCommerce.Platform.Web/Controllers/HomeController.cs
src/VirtoCommerce.Platform.Web/Extensions/ApplicationBuilderExtensions.cs
src/VirtoCommerce.Platform.Web/Licensing/License.cs
src/VirtoCommerce.Platform.Web/Licensing/LicenseProvider.cs
tests/VirtoCommerce.Platform.Tests/Controllers/Api/LicensingControllerTests.cs
tests/VirtoCommerce.Platform.Tests/Licenseing/LicenseProviderTests.cs

https://virtocommerce.atlassian.net/browse/PT-45

PT-552 Use Assets IBlobStorage as Distributed storage for the license file

---

docs/fundamentals/extensibility/extending-domain-models.md

https://virtocommerce.atlassian.net/browse/PT-312

PT-314: Change extending-model doc with PolymorphJsonConverter info

---

src/VirtoCommerce.Platform.Web/Startup.cs

Remove type registration in generic converters for the `SearchCriteria`.

PT-323: Update Startup.cs

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/security.js

https://virtocommerce.atlassian.net/browse/PT-812

PT-812: Prevent working with expired password

---

src/VirtoCommerce.Platform.Core/Security/PasswordValidationResult.cs
src/VirtoCommerce.Platform.Security/Services/PasswordCheckService.cs
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-resetPassword.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/services/passwordValidationService.js
tests/VirtoCommerce.Platform.Tests/Security/PasswordCheckServiceTests.cs

https://virtocommerce.atlassian.net/browse/PT-504

PT-504: Update Password checker to match AspNetCore.Identity options

---

src/VirtoCommerce.Platform.Security/Services/PasswordCheckService.cs

PT-502: Change private to protected virtual

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/smartFloat.js

https://virtocommerce.atlassian.net/browse/PT-421

PT-422: Add validation to integer type

---

src/VirtoCommerce.Platform.Web/wwwroot/js/i18n/decorators.js

https://virtocommerce.atlassian.net/browse/PT-954

PT-954: Add integer validation for multivalue

---

build/CHANGELOG.md
build/Directory.Build.props
build/PlatformTools/Build.InitPlatform.cs
build/_build.csproj

https://virtocommerce.atlassian.net/browse/PT-959

PT-960: Add InitPlatform target

---

build/_build.csproj
src/VirtoCommerce.Platform.Assets.AzureBlobStorage/VirtoCommerce.Platform.Assets.AzureBlobStorage.csproj
src/VirtoCommerce.Platform.Assets.FileSystem/VirtoCommerce.Platform.Assets.FileSystem.csproj
src/VirtoCommerce.Platform.Caching/VirtoCommerce.Platform.Caching.csproj
src/VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj
src/VirtoCommerce.Platform.Data/VirtoCommerce.Platform.Data.csproj
src/VirtoCommerce.Platform.Hangfire/VirtoCommerce.Platform.Hangfire.csproj
src/VirtoCommerce.Platform.Modules/VirtoCommerce.Platform.Modules.csproj
src/VirtoCommerce.Platform.Security/VirtoCommerce.Platform.Security.csproj
tests/VirtoCommerce.Testing/VirtoCommerce.Testing.csproj

https://virtocommerce.atlassian.net/browse/PT-207

PT-207: Enable Source link support

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json

Jira: https://virtocommerce.atlassian.net/browse/PT-839

PT-840: Change default columns for customer-accounts-list.tpl.html 

---

src/VirtoCommerce.Platform.Web/PushNotifications/SignalRBuilderExtensions.cs

https://virtocommerce.atlassian.net/browse/PT-197

PT-198: Turn back use of setting "PushNotifications:RedisBackplane:ChannelName"

---

src/VirtoCommerce.Platform.Core/Security/ApplicationUserExtensions.cs

https://virtocommerce.atlassian.net/browse/PT-1208

PT-1208: Detect user changes when status is changing

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

PT-1310: Swagger validation fix №1

---

build/CHANGELOG.md
build/Docs/Targets.md
build/HelpProvider/Build.HelpProvider.cs
build/_build.csproj

Added -? parameter which shows help for the target.
for example: vc-build Install -?

PT-1280: add help parameter and docs

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Common.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/propertyValue-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/propertyValue-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/genericValueInput.js
src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/genericValueInput.tpl.html

https://virtocommerce.atlassian.net/browse/PT-673

PT-674 Add hide empty property values command

---

docs/fundamentals/essential-modularity.md

Documentation modularity update
https://virtocommerce.atlassian.net/browse/PT-416

PT-416: Add notice about copy with multiinstancy

---

docs/developer-guide/deploy-from-source-code.md
docs/developer-guide/deploy-module-from-source-code.md
docs/getting-started/connect-storefront-to-platform-v3.md
docs/getting-started/deploy-from-precompiled-binaries-windows.md

- Fix .net core link
- Fix connect to storefront
- Fix Deploy from source code
- FIx Deploy module from source code

CCIT-340: Update docs

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/security.js

https://virtocommerce.atlassian.net/browse/PT-1426

PT-1428: Fix UI to redirect to home page after password change

---

src/VirtoCommerce.Platform.Core/JsonConverters/PolymorphJsonConverter.cs

Jira: https://virtocommerce.atlassian.net/browse/PT-1443

PT-1447: Fix change Name to FullName

---

src/VirtoCommerce.Platform.Modules/Local/LocalStorageModuleCatalog.cs

Turn back local storage mark to avoid an issue when we have one Redis but different file storages.
https://virtocommerce.atlassian.net/browse/PT-1514

PT-1514: Turn back local storage mark

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/app.js

https://virtocommerce.atlassian.net/browse/PT-629

PT-629 Add default ui-grid options configurator

---

src/VirtoCommerce.Platform.Core/Extensions/EnumerableExtensions.cs
tests/VirtoCommerce.Platform.Core.Tests/Extensions/EnumerableExtensionsTests.cs
tests/VirtoCommerce.Platform.Core.Tests/PlatformCoreMockHelper.cs
tests/VirtoCommerce.Platform.Core.Tests/VirtoCommerce.Platform.Core.Tests.csproj
tests/VirtoCommerce.Platform.Tests/Assets/AzureBlobStorageProviderTests.cs
tests/VirtoCommerce.Testing/Helpers/MockHelper.cs

Jira: https://virtocommerce.atlassian.net/browse/PT-1244

PT-1471: Tests

---

VirtoCommerce.Platform.sln
tests/VirtoCommerce.Platform.Assets.AzureBlobStorage.Tests/AppConfiguration.cs
tests/VirtoCommerce.Platform.Assets.AzureBlobStorage.Tests/AzureBlobStorageProviderTests.cs
tests/VirtoCommerce.Platform.Assets.AzureBlobStorage.Tests/VirtoCommerce.Platform.Assets.AzureBlobStorage.Tests.csproj
tests/VirtoCommerce.Platform.Assets.FileSystem.Tests/FileSystemBlobStorageProviderTests.cs
tests/VirtoCommerce.Platform.Assets.FileSystem.Tests/VirtoCommerce.Platform.Assets.FileSystem.Tests.csproj
tests/VirtoCommerce.Platform.Caching.Tests/CancellableCacheRegionTests.cs
tests/VirtoCommerce.Platform.Caching.Tests/LastChangesServiceTests.cs
tests/VirtoCommerce.Platform.Caching.Tests/MemoryCacheExtensionTests.cs
tests/VirtoCommerce.Platform.Caching.Tests/MemoryCacheTestsBase.cs
tests/VirtoCommerce.Platform.Caching.Tests/PlatformMemoryCacheTests.cs
tests/VirtoCommerce.Platform.Caching.Tests/RedisPlatformMemoryCacheTests.cs
tests/VirtoCommerce.Platform.Caching.Tests/VirtoCommerce.Platform.Caching.Tests.csproj
tests/VirtoCommerce.Platform.Tests/VirtoCommerce.Platform.Tests.csproj

Jira: https://virtocommerce.atlassian.net/browse/PT-1249

PT-1249: Split project

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.tpl.html

https://virtocommerce.atlassian.net/browse/PT-1131

PT-1134: Rework edit dictionary values in the Platform Settings

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.tpl.html

https://virtocommerce.atlassian.net/browse/PT-1131

PT-1134: Minor update: turn off autocomplete, keyUp for numeric dictValue

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.tpl.html

https://virtocommerce.atlassian.net/browse/PT-1131

PT-1134: Fix validation on icon click

---

src/VirtoCommerce.Platform.Core/Security/ApplicationUser.cs
src/VirtoCommerce.Platform.Core/Security/Role.cs
src/VirtoCommerce.Platform.Web/Swagger/ExcludeRedundantDepsFilter.cs
src/VirtoCommerce.Platform.Web/Swagger/SwaggerServiceCollectionExtensions.cs

https://virtocommerce.atlassian.net/browse/PT-1371

PT-1371: Fix swagger smells

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_window-modals.sass

https://virtocommerce.atlassian.net/browse/PT-1531

PT-1532: Change default height

---

build/Build.cs
build/CHANGELOG.md
build/Directory.Build.props
build/Docs/Targets.md
build/HelpProvider/Build.HelpProvider.cs
build/_build.csproj

Updated Targets.md, Changelog.md
Fixed code coverage issue

VCI-40: Update docs

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/includes/_constants.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_header.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/pushNotifications/headerNotificationWidget.tpl.html

https://virtocommerce.atlassian.net/browse/PT-1933
PT-1933: Add scroll to the notification list
https://virtocommerce.atlassian.net/browse/PT-1940
PT-1940: Update notification list background, etc.

PT-1940: Update notification list background, etc.

---

tests/VirtoCommerce.Platform.Caching.Tests/CancellableCacheRegionTests.cs

https://virtocommerce.atlassian.net/browse/PT-1632

PT-1632: Fix blinking test

---

build/Build.cs
build/CHANGELOG.md
build/Directory.Build.props
build/PlatformTools/Build.PackageManager.cs

https://virtocommerce.atlassian.net/browse/PT-1789

PT-1790: Disabling dependency processing feature

---

src/VirtoCommerce.Platform.Data/ExportImport/PlatformExportImportManager.cs

Fix for the task [RS-1078](https://virtocommerce.atlassian.net/browse/RS-1078)

RS-1078: Fix modules data export

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_forms.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_window-modals.sass
src/VirtoCommerce.Platform.Web/wwwroot/images/contrast-logo.svg
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/templates/sampleDataInstallation.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/templates/modulesInstallation.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/dialogs/changePasswordDialog.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/dialogs/forgotPasswordDialog.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/dialogs/resetPasswordDialog.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/login/login.tpl.html

https://virtocommerce.atlassian.net/browse/PT-2003
before:
after:

PT-2003: Update Login dialog; Use contrast-logo.svg

---

module.ignore

https://virtocommerce.atlassian.net/browse/PT-2088

PT-2088: Remove scrutor from module.ignore

---

docs/index.md
src/VirtoCommerce.Platform.Modules/Local/LocalStorageModuleCatalog.cs
tests/VirtoCommerce.Platform.Tests/Modularity/ModulePlatformCompatibilityTests.cs

... in addition to plain compare
Bug:
https://virtocommerce.atlassian.net/browse/PT-1729

PT-1729: Check module platform dependency by semantic version 

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/genericValueInput.tpl.html

https://virtocommerce.atlassian.net/browse/PT-2203

PT-2203: Support isRequired for generic datepicker

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/dialogs/confirmDialog.js

Add 'backdrop' and 'keyboard' options for configure modals.
Add callback on modal dismiss action.

PT-2391: Improve dialogService functionality

---

docs/fundamentals/extensibility/blade-toolbar.md
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Common.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ru.VirtoCommerce.Common.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/assets/blades/asset-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/blade/bladeContainer.tpl.html

https://virtocommerce.atlassian.net/browse/PT-1934

PT-1936: Tooltip for toolbar command button

---

src/VirtoCommerce.Platform.Hangfire/Extensions/RecurringJobExtensions.cs
src/VirtoCommerce.Platform.Hangfire/SettingCronJob.cs
src/VirtoCommerce.Platform.Hangfire/SettingCronJobBuilder.cs

https://virtocommerce.atlassian.net/browse/PT-2215

PT-2215: Enable custom evaluator in SettingCronJob

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ru.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.tpl.html

Reverts VirtoCommerce/vc-platform#2306

Revert "PT-2561: Data import UI fixes"

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ru.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.tpl.html

https://virtocommerce.atlassian.net/browse/PT-638

PT-2561: Import ui fixes

---

src/VirtoCommerce.Platform.Web/Controllers/Api/OAuthAppsController.cs

https://virtocommerce.atlassian.net/browse/PT-2756

PT-2758 Delete OAuth Application fix

---

src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs

https://virtocommerce.atlassian.net/browse/PT-2717

PT-2719: Deny login to admin for customers

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/app.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.tpl.html

UI/UX update for the Lock account function

PT-2987: UI/UX update for the Lock account function

---

src/VirtoCommerce.Platform.Core/Modularity/IHasHostEnvironment.cs
src/VirtoCommerce.Platform.Core/Settings/ObjectSettingEntry.cs
src/VirtoCommerce.Platform.Core/Swagger/UploadFileAttribute.cs
src/VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj
src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/AssetsController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/OAuthAppsController.cs
src/VirtoCommerce.Platform.Web/Model/Security/OAuthAppSearchCriteria.cs
src/VirtoCommerce.Platform.Web/Model/Security/OAuthAppSearchResult.cs
src/VirtoCommerce.Platform.Web/Swagger/FileUploadOperationFilter.cs

Jira-link: https://virtocommerce.atlassian.net/browse/PT-3439
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Platform.3.73.0-pr-2334.zip

PT-3266: essential changes/prerequisites to start platform decoupling 

---

src/VirtoCommerce.Platform.Core/Common/AsyncLock.cs
tests/VirtoCommerce.Platform.Caching.Tests/MemoryCacheExtensionTests.cs
tests/VirtoCommerce.Platform.Core.Tests/Common/AsyncLockTests.cs

Jira-link: https://virtocommerce.atlassian.net/browse/PT-3490
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Platform.3.73.0-pr-2335.zip

PT-3490:  AsyncLock doesn't provide multi-threads exclusive access to synchronized resources

---

src/VirtoCommerce.Platform.Core/Caching/MemoryCacheExtensions.cs
src/VirtoCommerce.Platform.Core/Common/AsyncLock.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/ProfilesController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SettingController.cs
tests/VirtoCommerce.Platform.Caching.Tests/MemoryCacheExtensionTests.cs
tests/VirtoCommerce.Platform.Core.Tests/Common/AsyncLockTests.cs

Reverts VirtoCommerce/vc-platform#2336

PT-3490: Async lock

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.tpl.html

PT-1941: Unset padding top

---

src/VirtoCommerce.Platform.DistributedLock/IDistributedLockProvider.cs
src/VirtoCommerce.Platform.DistributedLock/NoLock/NoLockDistributedLockProvider.cs
src/VirtoCommerce.Platform.DistributedLock/Redis/RedLockDistributedLockProvider.cs
src/VirtoCommerce.Platform.Modules/Local/LocalStorageModuleCatalog.cs
src/VirtoCommerce.Platform.Web/Extensions/ApplicationBuilderExtensions.cs
src/VirtoCommerce.Platform.Web/Startup.cs

Just make correct spelling ExecuteSynhronized -> ExecuteSynchronized

PT-0: Fix "synchronized" spelling

---

src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
src/VirtoCommerce.Platform.Data/GenericCrud/SearchService.cs

PT-50: Update Generic Crud Services

---

docs/user-guide/configuration-settings.md

PT-3739 Documentation

---

src/VirtoCommerce.Platform.Web/Properties/launchSettings.json
src/VirtoCommerce.Platform.Web/appsettings.json

Updated appsettings.json to simplify https://virtocommerce.com/docs/latest/vc-quickstart/. 
Allows preventing appsettings.json modifications to get a working solution.
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Platform.3.77.0-pr-2366.zip

Updated appsettings.json

---

src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs

PT-4315  CrudService GetById exception fix

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/dateTime-picker.js

Add a drop-less feature to stop popping up the calendar. Add tooltip with the current datetime format.
https://virtocommerce.atlassian.net/browse/PT-2381

PT-2381: Add drop-less feature to stop popping up the calendar.

---

src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs
src/VirtoCommerce.Platform.Web/Startup.cs

1. allow all anonymous requests
2. deny all requests for Customer, where auth is needed

PT-4165: Allow issuing Tokens for Customer

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.js

PT-1945: Localize blade title for dictionary setting values

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.tpl.html

PT-2907: Add border to import label

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/export-main.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.js

PT-2906: Add selection buttons to import blade

---

src/VirtoCommerce.Platform.Web/Middleware/ApiErrorWrappingMiddleware.cs

Provide option to show user-friendly errors when running vc-platform in production mode
https://virtocommerce.atlassian.net/browse/PT-3771

PT-3771: Provide option to show user-friendly errors

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_window-modals.sass

PT-1510: Fix loader height on the Login screen

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.js

Fix incorrect behavior while adding new entries into dynamic value dictionary list
https://virtocommerce.atlassian.net/browse/PT-5054

PT-5054: Fix incorrect behavior while adding new entries

---

tests/VirtoCommerce.Platform.Tests/GenericCrud/CrudServiceMock.cs
tests/VirtoCommerce.Platform.Tests/GenericCrud/CrudServiceTests.cs
tests/VirtoCommerce.Platform.Tests/GenericCrud/TestChangeEvent.cs
tests/VirtoCommerce.Platform.Tests/GenericCrud/TestChangedEvent.cs
tests/VirtoCommerce.Platform.Tests/GenericCrud/TestEntity.cs
tests/VirtoCommerce.Platform.Tests/GenericCrud/TestModel.cs

Tests for GenericCRUD service
https://virtocommerce.atlassian.net/browse/PT-2164

PT-2164: Tests for GenericCRUD service

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/includes/_constants.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_cosmetic.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_menu.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_ui-grid.sass

PT-636: Partial UI update (only scrolls)

---

.github/workflows/e2e.yml
.github/workflows/main.yml
src/VirtoCommerce.Platform.Core/PlatformConstants.cs
src/VirtoCommerce.Platform.Core/PlatformOptions.cs
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json

Whitelist for File Extensions
https://virtocommerce.atlassian.net/browse/PT-5546

PT-5546: Whitelist for File Extensions

---

docker-compose.override.yml

Update elastic search to 7.15 version
https://virtocommerce.atlassian.net/browse/PT-5080

PT-5080: Update elastic search to 7.15 version

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_dialogs.sass

https://virtocommerce.atlassian.net/browse/PT-5570

PT-5570: Add paddings to dialog buttons

---

src/VirtoCommerce.Platform.Web/Controllers/Api/PlatformExportImportController.cs
src/VirtoCommerce.Platform.Web/Startup.cs

WebClient is replaced with HttpClientFactory
https://virtocommerce.atlassian.net/browse/PT-5474

PT-5474: HttpClientFactory is registered and used instead webClient

---

.github/workflows/publish_nugets.yml

Add publish nugets workflow

---

src/VirtoCommerce.Platform.Web/Startup.cs

Obsolete UseDatabaseErrorPage middleware is replaced with filter

PT-5830: Obsolete UseDatabaseErrorPage middleware is replaced with filter

---

src/VirtoCommerce.Platform.Core/Modularity/LocalStorageModuleCatalogOptions.cs
src/VirtoCommerce.Platform.Modules/Local/LocalStorageModuleCatalog.cs

PT-6241: Prevent reference assembly loading

---

docs/release-information/update-to-version-3-200/update-platform-and-modules-to-3-200.md

Fixed language, rewrote some phrases to sound more natural.

docs: Fix language

---

docs/release-information/update-to-version-3-200/update-platform-and-modules-to-3-200.md

PT-6212: Release notes

---

src/VirtoCommerce.Platform.Core/Common/ICountriesService.cs
src/VirtoCommerce.Platform.Data/Common/CountriesService.cs
src/VirtoCommerce.Platform.Data/Common/FileSystemCountriesService.cs
src/VirtoCommerce.Platform.Data/Extensions/ServiceCollectionExtensions.cs
src/VirtoCommerce.Platform.Data/VirtoCommerce.Platform.Data.csproj
tests/VirtoCommerce.Platform.Tests/Common/CountriesServiceTests.cs

New implementation of the countries service basing on third party nuget
https://virtocommerce.atlassian.net/browse/PT-5026

PT-5026: New implementation of the countries service basing on third party nuget

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/login/headerUserProfileWidget.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/login/headerUserProfileWidget.tpl.html

Do not allow password changing if password login is disabled
https://virtocommerce.atlassian.net/browse/PT-6372

PT-6372: Do not allow password changing if password login is disabled

---

src/VirtoCommerce.Platform.Core/Caching/CacheDisabler.cs
src/VirtoCommerce.Platform.Core/Caching/MemoryCacheExtensions.cs
tests/VirtoCommerce.Platform.Caching.Tests/CacheDisablerTests.cs

using (CacheDisabler.DisableCache()) {
// Data won't be saved to the cache inside this block.
}
https://virtocommerce.atlassian.net/browse/PT-4026

PT-4026: CacheDisabler

---

.github/workflows/main.yml
.github/workflows/pr-ci.yml
.github/workflows/pr-deploy.yml

Added new workflows.
* Platform PR build (pr-ci.yml)  - force on PR, build platform, run unit test, sonar code quality checks, and place docker image to cache
* Platform PR deploy (pr-deploy.yml) - force on PR labeled by `deploy-qa` label, get docker image from cache, push the image to ghcr.io, deploy platform to QA environment
Edited Platform CI (main.yml) - workflow does not run on PR

PT-4557: Docker tag in the platform in the branches

---

src/VirtoCommerce.Platform.Modules/Local/LocalStorageModuleCatalog.cs

https://virtocommerce.atlassian.net/browse/PT-6079

PT-6079: Exclude modules discovery path of manifest path checking

---

src/VirtoCommerce.Platform.Core/Settings/SettingDescriptor.cs

https://virtocommerce.atlassian.net/browse/PT-6860

Extend SettingDescriptor with new properties

---

src/VirtoCommerce.Platform.Web/Controllers/ExternalSignInController.cs

Assigning a type for the new AzureAD users from appsettings

PT-6390: Assigning a type for the new AzureAD users from appsettings

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

This fixes 400 (BadRequest) error on creating new user.

fix: Fix password validation issue on creating new user

---

src/VirtoCommerce.Platform.Core/Security/ClaimsPrincipalExtensions.cs

Add a version of the FindPermission method to gather all permissions from claims with the specific name.
https://virtocommerce.atlassian.net/browse/PT-6767

PT-6767: Gather multiple permissions from claims

---

src/VirtoCommerce.Platform.Web/Controllers/ExternalSignInController.cs

Mapping users by email when register via Azure AD

PT-6377: Mapping users by email when register via Azure AD

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_window-modals.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/setup/templates/setupWizard.tpl.html

Fix popup display when installing sample data

PT-6635: Fix popup display when installing sample data

---

src/VirtoCommerce.Platform.Core/PlatformConstants.cs

PT-7030: disallow upload executables

---

src/VirtoCommerce.Platform.Core/Caching/MemoryCacheExtensions.cs
src/VirtoCommerce.Platform.Core/Extensions/EnumerableExtensions.cs
src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs

Add missing response group to the cache key prefix.

Add response group to the cache key prefix

---

src/VirtoCommerce.Platform.Core/Extensions/DictionaryExtension.cs
src/VirtoCommerce.Platform.Core/GenericCrud/SearchServiceExtensions.cs
src/VirtoCommerce.Platform.Core/Security/IPermissionsRegistrarExtensions.cs
src/VirtoCommerce.Platform.Core/Settings/SettingsExtension.cs

Extension methods from real projects.
Example for the search service:
```csharp
var searchCriteria = new MyCriteria { Take = 100 };
await foreach (var searchResult in searchService.SearchBatches(searchCriteria))
{
// Process search result
}
```

Add extension methods

---

src/VirtoCommerce.Platform.Core/Caching/MemoryCacheExtensions.cs
src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs

Simplify signature and usage of GetOrLoadByIdsAsync()

---

src/VirtoCommerce.Platform.Web/Extensions/ApplicationBuilderExtensions.cs
src/VirtoCommerce.Platform.Web/Startup.cs

Anti-clickjacking is added to all responses

PT-7042: Anti-clickjacking is added to all responses

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/de.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ru.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_cosmetic.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settings-detail.tpl.html

Add collapsible tooltips in settings
https://virtocommerce.atlassian.net/browse/PT-2295

PT-2295: Add collapsible tooltips in settings

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/blade/bladeContainer.tpl.html

Checking of hide method is added for toolbar commands

PT7232: Checking of hide method is added for toolbar commands

---

.github/workflows/main.yml

ci: switch off sample data instalation

---

docs/v2.0/dev_docs/Fundamentals/Data-Import/02-building-custom-importer.md

docs: small corrections in class names

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

PT-7598: add comment on using Host header

---

src/VirtoCommerce.Platform.Caching/VirtoCommerce.Platform.Caching.csproj
src/VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj
src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

Update Azure Application Insights from deprecated 2.15 to latest 2.20.
https://virtocommerce.atlassian.net/browse/PT-7697

PT-7697: Update Azure Application Insights

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/export-main.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/exportImport-main.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.js

Fix permission requirements to properly handle basic import-export in admin UI
https://virtocommerce.atlassian.net/browse/PT-7204
https://virtocommerce.atlassian.net/browse/PT-7199

PT-7204: Fix permission requirements

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/systemInfo/blades/system-info.js

PT-7944: Download package.json button

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/includes/_constants.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_menu.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/app.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/menu/mainMenu.tpl.html

Fix padding of the collapsed main menu at the right side
|Before|After|
|----|----|
|![image](https://user-images.githubusercontent.com/9972421/174238926-54243481-2264-4305-8827-23578f69fce5.png)|![image](https://user-images.githubusercontent.com/9972421/174311387-08d5a108-b208-44bd-b6ec-119eec0091ed.png)|
https://virtocommerce.atlassian.net/browse/PT-8068

PT-8068: Fix padding of the collapsed main menu

---

src/VirtoCommerce.Platform.Web/Security/CustomUserValidator.cs
src/VirtoCommerce.Platform.Web/Startup.cs

PT-7852: UserName validation

---

src/VirtoCommerce.Platform.Core/PlatformConstants.cs
src/VirtoCommerce.Platform.Data/Settings/SettingsManager.cs

https://virtocommerce.atlassian.net/browse/PT-7908

PT-7908: add default value to FileExtensionsWhiteList setting

---

docs/user-guide/configuration-settings.md

AppInsights settings documentation

PT-8041: AppInsights settings documentation

---

src/VirtoCommerce.Platform.Hangfire/Extensions/ApplicationBuilderExtensions.cs
src/VirtoCommerce.Platform.Hangfire/VirtoCommerce.Platform.Hangfire.csproj

Enable logging to hangfire jobs.
Log records become available in the job details:
https://virtocommerce.atlassian.net/browse/PT-8031

PT-8031: Enable logging to Hangfire jobs

---

src/VirtoCommerce.Platform.Web/Startup.cs

Default healthcheck endpoint
https://virtocommerce.atlassian.net/browse/PT-8080

PT-8074: Default healthcheck endpoint

---

src/VirtoCommerce.Platform.Core/PlatformConstants.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-list.js

User should have type Customer by default. changing the default user to "Customer" when creating an account

PT-4812: User type Customer by default

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_cosmetic.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/blade/bladeContainer.tpl.html

Possibility to show blade custom icon

PT-8145: Possibility to show blade custom icon

---

docs/user-guide/configuration-settings.md

Authentication connection string

PT-8240: Authentication connection string

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/menu/mainMenu-list-content.tpl.html

Sort sub-menu items in "More" for admin ui

---

src/VirtoCommerce.Platform.Core/Settings/FixedSettings.cs
src/VirtoCommerce.Platform.Core/Settings/ObjectSettingEntry.cs
src/VirtoCommerce.Platform.Data/Settings/SettingsManager.cs
src/VirtoCommerce.Platform.Web/Startup.cs
src/VirtoCommerce.Platform.Web/appsettings.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settings-detail.tpl.html

Overriding platform settings from configuration

PT-8419: Overriding platform settings from configuration

---

docs/user-guide/configuration-settings.md

Documentation
Setting overriding documentation

PT-8419: Setting overriding documentation

---

src/VirtoCommerce.Platform.Core/ExportImport/ExportImportExtension.cs
src/VirtoCommerce.Platform.Core/ExportImport/PlatformExportManifest.cs
src/VirtoCommerce.Platform.Core/ExportImport/PlatformImportExportRequest.cs
src/VirtoCommerce.Platform.Data/ExportImport/PlatformExportImportManager.cs
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/export-main.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/export-main.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.js

Separate export options for the settings and dynamic properties

PT-8387: Separate export options for the settings and dynamic properties

---

src/VirtoCommerce.Platform.Core/Settings/SettingDescriptor.cs
src/VirtoCommerce.Platform.Data/Model/SettingEntity.cs

Make SettingDescriptor implementing IEntity to simplify usage in events catchers

fix: Make SettingDescriptor implementing IEntity 

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/wizards/newAccount/new-account-wizard.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/wizards/newAccount/new-account-wizard.tpl.html

https://virtocommerce.atlassian.net/browse/PT-8411

PT-8411: add select account types on user create blade

---

src/VirtoCommerce.Platform.Web/appsettings.json

Fix the license activation URL

fix: Fix the license activation URL

---

.github/workflows/pr-ci.yml

fix: Fix sonar workflow version

---

docs/developer-guide/user-manager.md

PT-8393: User manager documentation

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_menu.sass

https://virtocommerce.atlassian.net/browse/PT-7777

PT-7777: Filter dropdown UI update

---

.github/workflows/main.yml
src/VirtoCommerce.Platform.Security/Services/UserSearchService.cs

Add user roles to users search results

PT-8843: Add user roles to users search results

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/common/scope-value-pick-from-simple-list.js

PT-8906: Fix saving scope in permission

---

src/VirtoCommerce.Platform.Security/Repositories/SecurityDbContext.cs

Introduce constructor with non-generic options of SecurityDbContext to allow extension
https://virtocommerce.atlassian.net/browse/PT-8270

PT-8270: Introduce constructor with non-generic options of SecurityDbContext

---

tests/VirtoCommerce.Platform.Caching.Tests/CancellableCacheRegionTests.cs
tests/VirtoCommerce.Platform.Caching.Tests/MemoryCacheExtensionTests.cs
tests/VirtoCommerce.Platform.Caching.Tests/NotThreadSafeCollection.cs
tests/VirtoCommerce.Platform.Caching.Tests/PlatformMemoryCacheTests.cs
tests/VirtoCommerce.Platform.Caching.Tests/RedisPlatformMemoryCacheTests.cs

A try to fix blinking memory tests

PT-0000: A try to fix blinking memory tests

---

src/VirtoCommerce.Platform.Data/ZipFile/ZipFileWrapper.cs
src/VirtoCommerce.Platform.Web/Swagger/SwaggerServiceCollectionExtensions.cs

https://virtocommerce.atlassian.net/browse/PT-8990

PT-8990: Fix Sonar security issues

---

.github/workflows/platform-ci.yml
src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs

Add support for java script modules if assemblyFile and moduleType are empty in the module manifest.

Add support for java script modules

---

src/VirtoCommerce.Platform.Caching/VirtoCommerce.Platform.Caching.csproj
src/VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj
src/VirtoCommerce.Platform.Web/Telemetry/UserTelemetryInitializer.cs
src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

Upgrade AppInsights.
Fix UserTelemetryInitializer to allow always set AppInsights role/instance names.
https://virtocommerce.atlassian.net/browse/PT-9050
https://virtocommerce.atlassian.net/browse/PT-9001

PT-9050: Fix UserTelemetryInitializer, upgrade AppInsights

---

src/VirtoCommerce.Platform.Web/Security/Authentication/BasicAuthenticationHandler.cs
src/VirtoCommerce.Platform.Web/Security/Authentication/BasicAuthenticationOptions.cs
src/VirtoCommerce.Platform.Web/Security/Authorization/PermissionAuthorizationPolicyProvider.cs
src/VirtoCommerce.Platform.Web/Startup.cs

Technical equivalent of:
https://github.com/VirtoCommerce/vc-platform/pull/2568
(for artifact building, etc.)

feat: Add basic authentication (#2568)

---

src/VirtoCommerce.Platform.Security/HttpContextUserResolver.cs

PT-9274: read VirtoCommerce-Operator-User-Name header

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass

fix: Popup text displayed incorrectly when installing sample data.

PT-6997: Popup text displayed incorrectly when installing sample data

---

src/VirtoCommerce.Platform.Web/Startup.cs

https://virtocommerce.atlassian.net/browse/PT-8441

PT-8441: add 'Cyrillic' as supported encoding name

---

docs/release-information/update-to-version-3/update-module-from-platform-2.0-to-version-3.md

docs: Fix demo link as per PD-131

---

.github/workflows/platform-ci.yml
src/VirtoCommerce.Platform.Data/Settings/SettingsManager.cs

fix: Problem with importing sample data if there is no imported setting

PT-9766: Problem with importing sample data if there is no imported setting

---

docs/user-guide/configuration-settings.md
src/VirtoCommerce.Platform.Core/Security/PasswordOptionsExtended.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/Model/Security/PasswordChangeEnabledResult.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/resources/accounts.js
tests/VirtoCommerce.Platform.Web.Tests/Controllers/Api/SecurityControllerTests.cs

IdentityOptions:Password:PasswordChangeByAdminEnabled

PT-9783: disable admins change passwords for users in the system

---

src/VirtoCommerce.Platform.Data/GenericCrud/SearchService.cs

https://virtocommerce.atlassian.net/browse/PT-9862

PT-9862: Cache only IDs in SearchService

---

src/VirtoCommerce.Platform.Web/Startup.cs

PT-10265: move IExternalSigninService registration before modules initialization

---

src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
src/VirtoCommerce.Platform.Data/GenericCrud/SearchService.cs

https://virtocommerce.atlassian.net/browse/PT-10190

PT-10190: Improve caching extensibility in CRUD services

---

src/VirtoCommerce.Platform.Data/Extensions/DbContextCommandExtensions.cs

fix: The connection was not closed. The connection's current state is open. https://learn.microsoft.com/en-us/ef/ef6/fundamentals/connection-management#behavior-in-ef6-and-future-versions-1

PT-9873: The connection was not closed. The connection's current state is open

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/export-main.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.tpl.html

feat: Sort list of Modules on the export page by id: asc.

PT-10345: Sort list of Modules on export page by id: asc

---

src/VirtoCommerce.Platform.Web/Controllers/Api/PlatformExportImportController.cs

fix: application authorizes Export endpoint with the PlatformImport permission, instead of the PlatformExport permission.

PT-10580: Application authorizes Export endpoint with the PlatformImport permission

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/de.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ru.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/export-main.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/blades/import-main.tpl.html

Added and enabled dynamic properties for import/export operations.
- Updated the condition to start export operation when dynamic properties are selected
- Updated the condition to start import operation when dynamic properties are seleted
- Updated import blade to add the dynamic properties
Added localization messages for dynamic-props (Russian,English,German)

fixed import/export of dynamic properties

---

src/VirtoCommerce.Platform.Web/Controllers/Api/DiagnosticsController.cs
src/VirtoCommerce.Platform.Web/Startup.cs

https://virtocommerce.atlassian.net/browse/PT-10562
https://virtocommerce.atlassian.net/browse/PT-10568

PT-10562, PT-10568: fix error information disclosure and check environment for diagnostic endpoint

---

src/VirtoCommerce.Platform.Web/Azure/AzureAdOptions.cs
src/VirtoCommerce.Platform.Web/Security/AzureADExternalSignInProvider.cs
src/VirtoCommerce.Platform.Web/Security/MultitenantAzureADIssuerValidator.cs
src/VirtoCommerce.Platform.Web/Startup.cs

PT-10354: remove AzureAD SSO

---

src/VirtoCommerce.Platform.Core/Common/AnnonymousComparer.cs

Add optional parameter keyEqualityComparer to AnonymousComparer.Create to compare keys with equality comparer

Add optional parameter keyEqualityComparer to AnonymousComparer.Create

---

src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs

PT-10442: extract Commit into virtual method (CrudService)

---

src/VirtoCommerce.Platform.Core/Security/AuthorizationOptions.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

PT-10544: Update api controller

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/smartFloat.js

enrich number fraction display rules

---

src/VirtoCommerce.Platform.Web/Views/Shared/_Layout.cshtml

PT-10228: switch to use GA4

---

src/VirtoCommerce.Platform.Web/Controllers/Api/AppsController.cs
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_links-menu.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/menu/mainMenu.tpl.html

feat: Rename App Menu to Application. 
feat: Rename VC Platform to Commerce Manager.

PT-11197: Improve App Menu

---

src/VirtoCommerce.Platform.Core/Common/EnumUtility.cs
tests/VirtoCommerce.Platform.Core.Tests/Common/EnumUtilityTests.cs

Fix EnumUtility.SafeRemoveFlagFromEnumString

---

src/VirtoCommerce.Platform.Data/ExportImport/PlatformExportImportManager.cs

fix: Import Data on PostgreSql. Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone'

PT-11328: Import Data on PostgreSql

---

src/VirtoCommerce.Platform.Web/Startup.cs

fix: Revert back PT-10895 by multiple issues with XAPI and UserManager

PT-11459: Revert back PT-10895 by multiple issues with XAPI and UserManager

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-list.tpl.html

https://virtocommerce.atlassian.net/browse/PT-11367

PT-11367: fix roles list sorting

---

src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

fix: add System.Diagnostics.PerformanceCounter.dll

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
tests/VirtoCommerce.Platform.Web.Tests/Controllers/Api/SecurityControllerTests.cs

- See UserManager(of TUser).ValidatePasswordAsync

Consistent password verification in the SecurityController

---

src/VirtoCommerce.Platform.Data/DynamicProperties/ServiceCollectionExtenions.cs
src/VirtoCommerce.Platform.Data/Validators/DynamicPropertyTypeValidator.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/DynamicPropertiesController.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/dynamicProperty-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/dynamicProperty-detail.tpl.html

PT-12122: dynamic property validation

---

src/VirtoCommerce.Platform.Core/Security/ApplicationUser.cs
src/VirtoCommerce.Platform.Data.MySql/Migrations/Security/20230608092308_AddLastLoginDate.Designer.cs
src/VirtoCommerce.Platform.Data.MySql/Migrations/Security/20230608092308_AddLastLoginDate.cs
src/VirtoCommerce.Platform.Data.MySql/Migrations/Security/SecurityDbContextModelSnapshot.cs
src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Security/20230608092144_AddLastLoginDate.Designer.cs
src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Security/20230608092144_AddLastLoginDate.cs
src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Security/SecurityDbContextModelSnapshot.cs
src/VirtoCommerce.Platform.Data.SqlServer/Migrations/Security/20230606180711_AddLastLoginDate.Designer.cs
src/VirtoCommerce.Platform.Data.SqlServer/Migrations/Security/20230606180711_AddLastLoginDate.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.tpl.html

PT-12376: Add last login date

---

src/VirtoCommerce.Platform.Core/Common/SemanticVersion.cs
src/VirtoCommerce.Platform.Security/ExternalSignin/IExternalSignInProvider.cs
src/VirtoCommerce.Platform.Web/Azure/AzureAdOptions.cs
src/VirtoCommerce.Platform.Web/Security/AzureADExternalSignInProvider.cs
src/VirtoCommerce.Platform.Web/Security/ExternalSigninService.cs

add default role to app settings

---

src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Security/20221128141520_Initial.cs

fix: Failure on empty PostgreSQL DB initialization. https://github.com/VirtoCommerce/vc-platform/issues/2678

PT-12895: Failure on empty PostgreSQL DB initialization

---

src/VirtoCommerce.Platform.Web/PushNotifications/PushNotificationHub.cs
src/VirtoCommerce.Platform.Web/PushNotifications/PushNotificationManager.cs
src/VirtoCommerce.Platform.Web/PushNotifications/PushNotificationUserIdProvider.cs
src/VirtoCommerce.Platform.Web/PushNotifications/SignalRBuilderExtensions.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/app.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/pushNotifications/pushNotifications.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/pushNotifications/resources/signalRHubProxy.js

https://virtocommerce.atlassian.net/browse/PT-11514

PT-11514: Users should not see other people's notifications

---

src/VirtoCommerce.Platform.Core/Extensions/SearchServiceExtensions.cs
src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
src/VirtoCommerce.Platform.Data/GenericCrud/SearchService.cs

- Add new extension methods: SearchAll(), SearchAllNoClone()
- Use List<T> in search result
- Fix search criteria corruption
- Don't call LoadEntities() with empty ids list
https://virtocommerce.atlassian.net/browse/PT-12559

PT-12559: Improve generic CRUD services

---

.gitignore
src/VirtoCommerce.Platform.Core/DynamicProperties/IDynamicPropertyDictionaryItemsSearchService.cs
src/VirtoCommerce.Platform.Core/DynamicProperties/IDynamicPropertySearchService.cs
src/VirtoCommerce.Platform.Core/Extensions/SearchServiceExtensions.cs
src/VirtoCommerce.Platform.Core/GenericCrud/ISearchService.cs
src/VirtoCommerce.Platform.Core/Security/Search/IUserApiKeySearchService.cs
src/VirtoCommerce.Platform.Core/Settings/ISettingsSearchService.cs
src/VirtoCommerce.Platform.Core/Settings/SettingsSearchCriteria.cs
src/VirtoCommerce.Platform.Core/Settings/SettingsSearchResult.cs
src/VirtoCommerce.Platform.Data/DynamicProperties/DynamicPropertyDictionaryItemsSearchService.cs
src/VirtoCommerce.Platform.Data/DynamicProperties/DynamicPropertyMetaDataResolver.cs
src/VirtoCommerce.Platform.Data/DynamicProperties/DynamicPropertySearchService.cs
src/VirtoCommerce.Platform.Data/ExportImport/PlatformExportImportManager.cs
src/VirtoCommerce.Platform.Data/Settings/SettingsSearchService.cs
src/VirtoCommerce.Platform.Security/Services/UserApiKeySearchService.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/DynamicPropertiesController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/PushNotificationController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SettingController.cs

https://virtocommerce.atlassian.net/browse/PT-13018

PT-13018: Don't use int.MaxValue with search services

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/exportImport/exportImport.js

https://virtocommerce.atlassian.net/browse/PT-13398

PT-13398: Fix condition for 'Import sample data' widget

---

src/VirtoCommerce.Platform.Web/Controllers/Api/DiagnosticsController.cs
src/VirtoCommerce.Platform.Web/Model/Diagnostics/SystemInfo.cs
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/systemInfo/blades/system-info.tpl.html

feat: Extend Platform Information with Environment Mode.

PT-13778: Extend Platform Information with Environment Mode

---

src/VirtoCommerce.Platform.Web/Controllers/Api/DynamicPropertiesController.cs

https://virtocommerce.atlassian.net/browse/PT-13847

PT-13847: Return all dictionary items for a dynamic property

---

src/VirtoCommerce.Platform.Security/ConfigureSecurityStampValidatorOptions.cs
src/VirtoCommerce.Platform.Security/Extensions/MergeClaimsIdentityExtensions.cs
src/VirtoCommerce.Platform.Web/Startup.cs

fix: SSO is reset to Password after some period by implementing SecurityStampValidatorOptions.OnRefreshingPrincipal

PT-13919: SSO is reset to Password after some period.

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

fix: Update Account resets PasswordHash and SecurityStamp to null if Setting ReturnPasswordHash is True.

PT-13960: Resets Password if Setting ReturnPasswordHash is True

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_cosmetic.sass

fix: Blade icon style. The image is made to fill the box, while preserving its aspect ratio.

PT-13927: Fix blade icon style

---

src/VirtoCommerce.Platform.Web/Controllers/Api/PlatformExportImportController.cs

fix: Null in push notification after import sample data.

PT-14007: Null in push notification after import sample data

---

Directory.Build.props
src/VirtoCommerce.Platform.Web/Infrastructure/HealthCheck/ModulesHealthChecker.cs
src/VirtoCommerce.Platform.Web/Startup.cs

feat: ModulesHealthChecker returns Unhealthy (503 status) by default
feat: Add information about failed modules into log.

PT-13900: ModulesHealthChecker returns Unhealthy (503 status)

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/de.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ru.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/pushNotifications/blade/history.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/pushNotifications/blade/history.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/pushNotifications/blade/historyDetailDefault.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/pushNotifications/blade/historyDetailDefault.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/pushNotifications/pushNotifications.js

fix: Fix UI for default push notification details blade.

PT-14204: Fixs UI for default push notification details

---

src/VirtoCommerce.Platform.Web/Controllers/ExternalSignInController.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/app.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/services/auth.js

fix: Swith to Cookies Auth for back office and token for API because mix of cookie and token leads to unexpected behaviour.

PT-14196: Use Cookies Auth for back office

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/widget/widget.js
src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/metaform.js

feat: Added unregisterWidget method, which allows you to remove a specific widget from a container.
feat:  Added getWidgets method to retrieve the collection of widgets associated with a particular container.
feat: Added clearWidgets method to clear widgets associated with a particular container.
feat: Added unregisterMetaFields. This method allows you to remove a specific meta field from a given meta form by specifying the meta field to be unregistered.
feat: Added clearMetaFields: This method allows you to clear all registered meta fields for a specific meta form.

PT-14265: Provide better management and flexibility when working with metaFormsService and widgetService

---

src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs

fix: Reset password link in doesn't work. Opens blank page.

PT-14337: Reset password link in doesn't work

---

src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs

fix: Authorization in swager breaks Backoffice authorization. The Token request doesn't set any Authorization cookie more.

PT-14463: Authorization in swager UI breaks Backoffice authorization.

---

src/VirtoCommerce.Platform.Core/Common/SemanticVersion.cs
src/VirtoCommerce.Platform.Web/Startup.cs
tests/VirtoCommerce.Platform.Tests/Common/SemanticVersionTests.cs

fix: ForbidResult return 401 http status code instead of 403, it forced redirect to login page.

PT-14520: ForbidResult should return 403 http status code

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/left-click-menu.js

fix: Menu is still being placed above the top of the screen

PT-14431: Menu is still being placed above the top of the screen

---

src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs

PT-14414: reset cache for old models in CRUD service

---

src/VirtoCommerce.Platform.Core/Common/KeyValue.cs
src/VirtoCommerce.Platform.Core/Settings/ILocalizableSettingService.cs
src/VirtoCommerce.Platform.Core/Settings/LocalizableSetting.cs
src/VirtoCommerce.Platform.Core/Settings/LocalizableSettingsAndLanguages.cs
src/VirtoCommerce.Platform.Data/Settings/LocalizableSettingService.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/LocalizableSettingsController.cs
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/localizable-setting-value-details.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/localizable-setting-value-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/directives/setting-value-select.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/directives/setting-value-select.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/resources/localizable-settings-api.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/services/localizable-setting-service.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/services/setting-translate-filter.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/settings.js

https://virtocommerce.atlassian.net/browse/PT-13976

PT-13976: Improve settings localization

---

src/VirtoCommerce.Platform.Core/Notifications/IEmailSender.cs
src/VirtoCommerce.Platform.Core/Security/Events/UserRequestPasswordResetEvent.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
tests/VirtoCommerce.Platform.Web.Tests/Controllers/Api/SecurityControllerTests.cs

PT-14083: send event instead of email

---

src/VirtoCommerce.Platform.Hangfire/VirtoCommerce.Platform.Hangfire.csproj
src/VirtoCommerce.Platform.Modules/LoadContextAssemblyResolver.cs
tests/VirtoCommerce.Platform.Caching.Tests/VirtoCommerce.Platform.Caching.Tests.csproj
tests/VirtoCommerce.Platform.Core.Tests/VirtoCommerce.Platform.Core.Tests.csproj
tests/VirtoCommerce.Platform.Tests/VirtoCommerce.Platform.Tests.csproj
tests/VirtoCommerce.Platform.Web.Tests/VirtoCommerce.Platform.Web.Tests.csproj
tests/VirtoCommerce.Testing/VirtoCommerce.Testing.csproj

https://virtocommerce.atlassian.net/browse/VP-8480

VP-8480: Fix startup errors

---

docs/techniques/how-scale-out-platform-on-azure.md
src/VirtoCommerce.Platform.Web/PushNotifications/PushNotificationManager.cs
src/VirtoCommerce.Platform.Web/PushNotifications/Scalability/PushNotificationSynchronizerTask.cs
src/VirtoCommerce.Platform.Web/appsettings.json

fix: Incorrect list of events in System event blade on multiinstance configuration. Read more about scaling configuration on https://virtocommerce.com/docs/latest/techniques/how-scale-out-platform-on-azure/

PT-14881: Incorrect list of events in System event blade

---

src/VirtoCommerce.Platform.Core/Settings/LocalizableSetting.cs
src/VirtoCommerce.Platform.Data/Settings/LocalizableSettingService.cs
src/VirtoCommerce.Platform.Web/appsettings.json
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/localizable-setting-value-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/directives/setting-value-select.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/services/localizable-setting-service.js

https://virtocommerce.atlassian.net/browse/PT-14913

PT-14913: Support non-localizable settings in va-setting-value-select

---

azuredeploy.json

Set  dotnet version 8 in ARM template used for deploy to Azure. Test was made using modules.json file attached to the task in Jira.
https://virtocommerce.atlassian.net/browse/PT-15028

#PT-15028: Change net version in ARM template

---

src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
src/VirtoCommerce.Platform.Web/appsettings.json

feat: bump Swashbuckle.AspNetCore.SwaggerGen to 6.5.0

PT-14740: bump Swashbuckle.AspNetCore.SwaggerGen to 6.5.0

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/uiScroll.js

when value is empty fetchNext is invoked

VCST-147: disable pagination

---

src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_dialogs.sass

Write new CSS rules in accordance with a new standarts for Chrome 121.

VCST-352: fix scrollbar style for popup message

---

src/VirtoCommerce.Platform.Data.SqlServer/VirtoCommerce.Platform.Data.SqlServer.csproj

https://virtocommerce.atlassian.net/browse/VCST-383

VCST-383: Update dependencies

---

src/VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj
src/VirtoCommerce.Platform.Data.SqlServer/VirtoCommerce.Platform.Data.SqlServer.csproj
src/VirtoCommerce.Platform.Hangfire/VirtoCommerce.Platform.Hangfire.csproj
src/VirtoCommerce.Platform.Security/VirtoCommerce.Platform.Security.csproj
src/VirtoCommerce.Platform.Web/Startup.cs
src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
tests/VirtoCommerce.Platform.Caching.Tests/VirtoCommerce.Platform.Caching.Tests.csproj
tests/VirtoCommerce.Platform.Core.Tests/VirtoCommerce.Platform.Core.Tests.csproj
tests/VirtoCommerce.Platform.Tests/VirtoCommerce.Platform.Tests.csproj
tests/VirtoCommerce.Platform.Web.Tests/VirtoCommerce.Platform.Web.Tests.csproj
tests/VirtoCommerce.Testing/VirtoCommerce.Testing.csproj

https://virtocommerce.atlassian.net/browse/VCST-385

VCST-385: Update dependencies

---

src/VirtoCommerce.Platform.Web/Swagger/OpenIDEndpointDescriptionFilter.cs

https://virtocommerce.atlassian.net/browse/VCST-608

VCST-608: add storeId field to swagger schema for POST connect/token

---

src/VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj
src/VirtoCommerce.Platform.Hangfire/VirtoCommerce.Platform.Hangfire.csproj
src/VirtoCommerce.Platform.Security/VirtoCommerce.Platform.Security.csproj
src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
tests/VirtoCommerce.Platform.Caching.Tests/VirtoCommerce.Platform.Caching.Tests.csproj
tests/VirtoCommerce.Platform.Core.Tests/VirtoCommerce.Platform.Core.Tests.csproj
tests/VirtoCommerce.Platform.Tests/VirtoCommerce.Platform.Tests.csproj
tests/VirtoCommerce.Platform.Web.Tests/VirtoCommerce.Platform.Web.Tests.csproj
tests/VirtoCommerce.Testing/VirtoCommerce.Testing.csproj

https://virtocommerce.atlassian.net/browse/VCST-388

VCST-388: Update dependencies

---

src/VirtoCommerce.Platform.Modules/AssemblyLoading/PlatformInformation.cs

VCST-662: fix folder

---

src/VirtoCommerce.Platform.Core/Settings/ObjectSettingEntry.cs
src/VirtoCommerce.Platform.Core/Settings/SettingDescriptor.cs
src/VirtoCommerce.Platform.Data.MySql/Readme.md
src/VirtoCommerce.Platform.Data.PostgreSql/Readme.md
src/VirtoCommerce.Platform.Data.SqlServer/Readme.md

feat: Extends SettingDescriptor with IsPublic property. Flag indicates that this settings is accessible for client application via XAPI. By default, false.

VCST-596: Extend SettingDescriptor with IsPublic property.

---

azuredeploy.json

Changed default SKU for the platform web app to escape possible faults during platform installation and set property for the storage account to fix sample data import (https://virtocommerce.atlassian.net/browse/VP-8546).

Vp 8546 azure button

---

src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs

VCST-820: fix revoke token for customer

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-detail.tpl.html

fix: Resolves the issue that the last login date and time indicates the current date/time instead of NA if last login date is null or undefined.

VCST-879: The last login date and time indicates the current date/time instead of NA

---

README.md
azureDeployWebAppForContainer.json

Add an ARM template for the platform deployment using Azure web app for containers.

VCST-819: Deploy to Azure From Virto Start Container

---

.gitignore
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/main.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_blade-header.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_vc-badge.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/modules-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/blade/bladeContainer.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/account-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-list.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/localizable-setting-value-list.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/setting-dictionary.tpl.html

Improve Counter design.
Long titles:
https://virtocommerce.atlassian.net/browse/VCST-567

VCST-567: redesign count

---

src/VirtoCommerce.Platform.Web/wwwroot/js/common/dialogs/templates/errorDialog.tpl.html

https://virtocommerce.atlassian.net/browse/VCST-593

VCST-593: support multiline messages on error dialogs

---

src/VirtoCommerce.Platform.Data.MySql/VirtoCommerce.Platform.Data.MySql.csproj

feat: Update Pomelo.EntityFrameworkCore.MySql from beta to 8.0.2 latest release.

VCST-922: Update Pomelo.EntityFrameworkCore.MySql

---

src/VirtoCommerce.Platform.Data.MySql/HealthCheck/MySqlHealthCheck.cs
src/VirtoCommerce.Platform.Data.MySql/HealthCheck/MySqlHealthCheckBuilderExtensions.cs
src/VirtoCommerce.Platform.Data.MySql/HealthCheck/MySqlHealthCheckOptions.cs
src/VirtoCommerce.Platform.Data.PostgreSql/HealthCheck/NpgSqlHealthCheck.cs
src/VirtoCommerce.Platform.Data.PostgreSql/HealthCheck/NpgSqlHealthCheckBuilderExtensions.cs
src/VirtoCommerce.Platform.Data.PostgreSql/HealthCheck/NpgSqlHealthCheckOptions.cs
src/VirtoCommerce.Platform.Data.SqlServer/HealthCheck/SqlServerHealthCheck.cs
src/VirtoCommerce.Platform.Data.SqlServer/HealthCheck/SqlServerHealthCheckBuilderExtensions.cs
src/VirtoCommerce.Platform.Data.SqlServer/HealthCheck/SqlServerHealthCheckOptions.cs
src/VirtoCommerce.Platform.Web/Infrastructure/HealthCheck/RedisHealthCheck.cs
src/VirtoCommerce.Platform.Web/Startup.cs

* health checker for ms sql
* health checker for postgre sql
* health checker for my sql

VCST-913: add health checkers for databases

---

src/VirtoCommerce.Platform.Core/Extensions/ModuleCatalogExtensions.cs
src/VirtoCommerce.Platform.Core/Modularity/IHasModuleCatalog.cs
src/VirtoCommerce.Platform.Core/Modularity/IOptionalDependency.cs
src/VirtoCommerce.Platform.Core/Modularity/ManifestDependency.cs
src/VirtoCommerce.Platform.Core/Modularity/ManifestModuleInfo.cs
src/VirtoCommerce.Platform.Core/Modularity/ModuleCatalog.cs
src/VirtoCommerce.Platform.Core/Modularity/ModuleIdentity.cs
src/VirtoCommerce.Platform.Data/ExportImport/PlatformExportImportManager.cs
src/VirtoCommerce.Platform.Modules/JsonConverters/ModuleIdentityJsonConverter.cs
src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs
src/VirtoCommerce.Platform.Modules/OptionalDependencyManager.cs
src/VirtoCommerce.Platform.Web/Model/Modularity/ModuleDescriptor.cs
src/VirtoCommerce.Platform.Web/Startup.cs
src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_base-modules.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/app.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/module-detail.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/module-detail.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/modularity.js

Image tag:
3.824.0-pr-2787-088f-vcst-509-optional-modules-088f457b

VCST-509: optional modules support

---

src/VirtoCommerce.Platform.Data/Settings/LocalizableSettingService.cs

https://virtocommerce.atlassian.net/browse/VCST-786
Image tag:
3.828.0-pr-2796-f323-vcst-786-f323090c

VCST-786: Save only changed localization items

---

src/VirtoCommerce.Platform.Core/Bus/HandlerWrapper.cs
src/VirtoCommerce.Platform.Core/Bus/IHandlerRegistrar.cs
src/VirtoCommerce.Platform.Core/Bus/InProcessBus.cs
src/VirtoCommerce.Platform.Core/Events/ApplicationBuilderExtensions.cs
src/VirtoCommerce.Platform.Core/Events/IEventHandlerRegistrar.cs
src/VirtoCommerce.Platform.Hangfire/Extensions/ApplicationBuilderExtensions.cs
src/VirtoCommerce.Platform.Hangfire/Extensions/RecurringJobExtensions.cs
src/VirtoCommerce.Platform.Hangfire/Extensions/ServiceCollectionExtensions.cs
src/VirtoCommerce.Platform.Hangfire/IRecurringJobService.cs
src/VirtoCommerce.Platform.Hangfire/RecurringJobService.cs
src/VirtoCommerce.Platform.Hangfire/SettingCronJobBuilder.cs
src/VirtoCommerce.Platform.Web/Security/ApplicationBuilderExtensions.cs
tests/VirtoCommerce.Platform.Tests/Events/EventHandlerTests.cs
tests/VirtoCommerce.Platform.Tests/UnitTests/JobSettingsWatcherUnitTests.cs

```csharp
using VirtoCommerce.Platform.Core.Events;
public class Module : IModule, IHasConfiguration
{
public void PostInitialize(IApplicationBuilder appBuilder)
{
// Unregister specific handler
appBuilder.UnregisterEventHandler<UserLoginEvent, LogChangesUserChangedEventHandler>();
// Unregister all handlers for specific event
appBuilder.UnregisterEventHandlers<UserLoginEvent>();
// Unregister all handlers for all events
appBuilder.UnregisterAllEventHandlers();
}
}
```
https://virtocommerce.atlassian.net/browse/VCST-1230
Image tag:
3.829.0-pr-2797-209f-vcst-1230-209f5f08

VCST-1230: Add UnregisterEventHandler()

---

src/VirtoCommerce.Platform.Modules/Local/LocalStorageModuleCatalog.cs
src/VirtoCommerce.Platform.Web/appsettings.json

Image tag:
3.830.0-pr-2801-d28a-vcst-1286-d28af673

VCST-1286: get platform from native dll before copying

---

src/VirtoCommerce.Platform.Web/appsettings.json

Image tag:
3.832.0-pr-2803-40a4-vcst-1282-40a47683

VCST-1282: add default main menu state

---

src/VirtoCommerce.Platform.Core/PlatformUIOptions.cs
src/VirtoCommerce.Platform.Web/Controllers/HomeController.cs
src/VirtoCommerce.Platform.Web/Startup.cs
src/VirtoCommerce.Platform.Web/appsettings.json

The setting: 
```json
"VirtoCommerce": {
"PlatformUI": {
"Enable": true
}
}
```
Image tag:
3.832.0-pr-2802-83fe-vcst-1279-83fe9595

VCST-1279: add platform UI options to disable Platform UI

---

src/VirtoCommerce.Platform.Web/Controllers/Api/AppsController.cs

fix: App with Permission Not Displayed in App List After Sign-In.
Image tag:
3.833.0-pr-2808-abc1-vcst-1392-abc1b5e7

VCST-1392: App with Permission Not Displayed in App List After Sign-In

---

src/VirtoCommerce.Platform.Data.MySql/Migrations/Data/20240611091800_MakeSettingIdNotNullable.Designer.cs
src/VirtoCommerce.Platform.Data.MySql/Migrations/Data/20240611091800_MakeSettingIdNotNullable.cs
src/VirtoCommerce.Platform.Data.MySql/Migrations/Data/PlatformDbContextModelSnapshot.cs
src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Data/20240611091908_MakeSettingIdNotNullable.Designer.cs
src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Data/20240611091908_MakeSettingIdNotNullable.cs
src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Data/PlatformDbContextModelSnapshot.cs
src/VirtoCommerce.Platform.Data.SqlServer/Migrations/Data/20240611091951_MakeSettingIdNotNullable.Designer.cs
src/VirtoCommerce.Platform.Data.SqlServer/Migrations/Data/20240611091951_MakeSettingIdNotNullable.cs
src/VirtoCommerce.Platform.Data/Repositories/PlatformDbContext.cs

https://virtocommerce.atlassian.net/browse/VCST-1364
Image tag:
3.834.0-pr-2806-443f-vcst-1364-443f9ee3

VCST-1364: fix: Deleted setting values remained in the PlatformSettingValue table

---

src/VirtoCommerce.Platform.Security/CustomUserManager.cs

- Add virtual ConfigureCache method to CustomUserManager
- Refactor CustomUserManager tasks
Image tag:
3.845.0-pr-2821-4fad-vcps-user-manager-4fad68d9

feat: Add virtual ConfigureCache method to CustomUserManager

---

.github/workflows/platfotm-owasp.yml

Disable on push trigger

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/security.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/services/auth.js

https://virtocommerce.atlassian.net/browse/VCST-1620
Image tag:
ghcr.io/VirtoCommerce/platform:3.851.0-pr-2831-7656-vcst-1620-7656c09c

fix: Fix ArgumentNullException when using autofill on the sign in page

---

src/VirtoCommerce.Platform.Web/appsettings.json

feat: Extends appsettings.json with Stores sections. This enhancement streamlines the process for web applications to dynamically retrieve and store information based on the domain name provided in the query, then store id from the response can be used for other queries and mutations.
https://virtocommerce.atlassian.net/browse/VCST-1761
Image tag:
ghcr.io/VirtoCommerce/platform:3.851.0-pr-2833-bff0-vcst-1761-bff0b3aa

VCST-1761: Extend Platform Store Settings

---

src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/main.sass
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_contact-admin.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/app.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/dialogs/contact-admin.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/security.js

if user doesn't have any permissions and he isn't an administrator, he redirects to "/contaxt-admin" page with correspond message
https://virtocommerce.atlassian.net/browse/VCST-1280
Image tag:
ghcr.io/VirtoCommerce/platform:3.851.0-pr-2830-2109-vcst-1280-21097c09

VCST-1280: display message when user doesn't have permissions

---

src/VirtoCommerce.Platform.Web/Controllers/ExternalSignInController.cs

https://virtocommerce.atlassian.net/browse/VCST-1807
Image tag:
ghcr.io/VirtoCommerce/platform:3.852.0-pr-2836-0929-vcst-1807-0929be08

VCST-1807: Add returnUrl argument to external sign out

---

src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

https://virtocommerce.atlassian.net/browse/VCST-1593
Image tag:
ghcr.io/VirtoCommerce/platform:3.854.0-pr-2841-b5f8-vcst-1593-b5f88895

VCST-1593: Remove System.Diagnostics.PerformanceCounter

---

src/VirtoCommerce.Platform.Data.MySql/Migrations/Security/20241003120247_UpdateOpenIddict.Designer.cs
src/VirtoCommerce.Platform.Data.MySql/Migrations/Security/20241003120247_UpdateOpenIddict.cs
src/VirtoCommerce.Platform.Data.MySql/Migrations/Security/SecurityDbContextModelSnapshot.cs
src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Security/20241003120234_UpdateOpenIddict.Designer.cs
src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Security/20241003120234_UpdateOpenIddict.cs
src/VirtoCommerce.Platform.Data.SqlServer/Migrations/Security/20241003101239_UpdateOpenIddict.Designer.cs
src/VirtoCommerce.Platform.Data.SqlServer/Migrations/Security/20241003101239_UpdateOpenIddict.cs
src/VirtoCommerce.Platform.Data.SqlServer/Migrations/Security/SecurityDbContextModelSnapshot.cs
src/VirtoCommerce.Platform.Security/VirtoCommerce.Platform.Security.csproj
src/VirtoCommerce.Platform.Web/Controllers/Api/OAuthAppsController.cs
src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

https://virtocommerce.atlassian.net/browse/VCST-1592
Image tag:
ghcr.io/VirtoCommerce/platform:3.855.0-pr-2842-adf2-vcst-1592-adf2df25

VCST-1592: Update OpenIddict

---

src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

Dependency Azure.Core was upgraded to the latest version (1.44.1)
Image tag:
ghcr.io/VirtoCommerce/platform:3.857.0-pr-2854-2d55-upgrade-azure-core-1.44.1-2d55e643

Upgrade Azure.Core dependency

---

src/VirtoCommerce.Platform.Web/Startup.cs

Image tag:
ghcr.io/VirtoCommerce/platform:3.862.0-pr-2856-02a0-fix-naming-02a09e2e

chore: Fix naming

---

src/VirtoCommerce.Platform.Web/Controllers/Api/ModulesController.cs
src/VirtoCommerce.Platform.Web/Startup.cs

fix: Fixed Module Img Url and Modules path in debug VS mode
https://virtocommerce.atlassian.net/browse/VCST-2120
Image tag:
ghcr.io/VirtoCommerce/platform:3.868.0-pr-2863-b4ba-vcst-2120-b4bab821

VCST-2120: Fix icon URL in module list

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settingGroup-list.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settings-detail-theme-login-screen-logo.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settings-detail-theme-login-screen-logo.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settings-detail-theme-logo.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settings-detail-theme-logo.tpl.html

fix: Improves setting's title.
https://virtocommerce.atlassian.net/browse/VCST-2405
Image tag:
ghcr.io/VirtoCommerce/platform:3.869.0-pr-2864-6e09-vcst-2405-6e0988cf

VCST-2405: Improves setting's title

---

src/VirtoCommerce.Platform.Web/Swagger/CustomSwaggerGenerator.cs
src/VirtoCommerce.Platform.Web/Swagger/SwaggerServiceCollectionExtensions.cs
src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

https://virtocommerce.atlassian.net/browse/VCST-1735
Image tag:
ghcr.io/VirtoCommerce/platform:3.871.0-pr-2868-db67-vcst-1735-db676d76

VCST-1735: Update Swashbuckle to version 7.2.0

---

src/VirtoCommerce.Platform.Web/appsettings.json

```json
{
"VirtoCommerce": {
"GraphQL": {
"ForbiddenAuthenticationTypes": [
"Identity.Application"
]
}
}
}
```
https://virtocommerce.atlassian.net/browse/VCST-1985
Image tag:
ghcr.io/VirtoCommerce/platform:3.875.0-pr-2873-3351-vcst-1985-33513284

VCST-1985: Add VirtoCommerce:GraphQL:ForbiddenAuthenticationTypes option

---

src/VirtoCommerce.Platform.Core/Common/LocalizedString.cs
tests/VirtoCommerce.Platform.Core.Tests/Common/LocalizedStringTests.cs

feat: Introduce LocalizedString class in VirtoCommerce.Platform.Core.Common namespace. This class manages localized strings using a dictionary with language codes.
https://virtocommerce.atlassian.net/browse/VCST-2486
Image tag:
ghcr.io/VirtoCommerce/platform:3.877.0-pr-2876-3b09-vcst-2486-3b09e5c6

VCST-2486: Add LocalizedString class for handling localized strings

---

src/VirtoCommerce.Platform.Security/Extensions/ClaimsPrincipalExtensions.cs
src/VirtoCommerce.Platform.Security/OpenIddict/ITokenRequestHandler.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs

https://virtocommerce.atlassian.net/browse/VCST-2630
Image tag:
ghcr.io/VirtoCommerce/platform:3.879.0-pr-2887-f4c3-vcst-2630-f4c305ee

VCST-2630: add token request handler

---

src/VirtoCommerce.Platform.Web/Startup.cs

By default Platform provides Debug and Console sinks. Additional sinks, like Seq, can be loaded via modules. This fixes the order of Serilog initialization: read platform Serilog config after all modules were loaded. 
https://virtocommerce.atlassian.net/browse/VCST-2785
Image tag:
ghcr.io/VirtoCommerce/platform:3.880.0-pr-2893-5003-vcst-2785-500391be

VCST-2785: load Serilog configuration after module initialize

---

.github/workflows/platform-ci.yml

Update owasp action version

---

src/VirtoCommerce.Platform.Web/Controllers/Api/ProfilesController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/Model/Profiles/UserProfile.cs
src/VirtoCommerce.Platform.Web/Model/Security/UserDetail.cs
src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_header.sass
src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/blade/bladeContainer.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/login/headerUserProfileWidget.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/login/headerUserProfileWidget.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/services/auth.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/userProfile/blades/userProfile.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/userProfile/blades/userProfile.tpl.html
src/VirtoCommerce.Platform.Web/wwwroot/js/app/userProfile/resources/userProfileApi.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/userProfile/services/userProfileIconService.js
src/VirtoCommerce.Platform.Web/wwwroot/js/app/userProfile/userProfile.js

feat: Added Member Icon to the header, changing icon in profile and reaction to icon's update
https://virtocommerce.atlassian.net/browse/VCST-2698
Image tag:
ghcr.io/VirtoCommerce/platform:3.881.0-pr-2891-48dc-vcst-2698-48dcf264

VCST-2698: Add member icon to the header

---

src/VirtoCommerce.Platform.Core/PlatformConstants.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/OAuthAppsController.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/PlatformExportImportController.cs

https://virtocommerce.atlassian.net/browse/VCST-2969
Image tag:
ghcr.io/VirtoCommerce/platform:3.885.0-pr-2907-fa07-vcst-2969-fa070e90

VCST-2969: Add missing permission checks

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/directives/setting-value-select.js
src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/uiScroll.js

https://virtocommerce.atlassian.net/browse/VCST-3571
Image tag:
ghcr.io/VirtoCommerce/platform:3.893.0-pr-2922-d8e4-vcst-3571-d8e4bd4c

VCST-3571: Fix ui-scroll-drop-down and va-setting-value-select

---

src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj

https://virtocommerce.atlassian.net/browse/VCST-3590
Image tag:
ghcr.io/VirtoCommerce/platform:3.894.0-pr-2924-671d-vcst-3590-671d2bd7

VCST-3590: Update Microsoft.Identity.Client Package

---

src/VirtoCommerce.Platform.Core/Domain/IHasLanguage.cs
src/VirtoCommerce.Platform.Core/Domain/LocalizedStringEntity.cs
src/VirtoCommerce.Platform.Data/Infrastructure/DbContextBase.cs
src/VirtoCommerce.Platform.Data/Model/LocalizedStringEntity.cs

Add LocalizedStringEntity abstract class.
Image tag:
ghcr.io/VirtoCommerce/platform:3.895.0-pr-2925-96c5-add-localizedstringentity-96c5def8

feat: Add LocalizedStringEntity abstract class.

---

src/VirtoCommerce.Platform.Data/Extensions/ApplicationBuilderExtensions.cs
src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
src/VirtoCommerce.Platform.Web/appsettings.json

fix: Prevents auditable fields from modifications. This ensures more accurate tracking of audit fields.
fix: Prevents PasswordExpired, LockoutEnabled, LockoutEnd, LastLoginDate, and LastPasswordChangedDate from modification via User API.
fix: Update ReturnPasswordHash setting in appsettings.json. Changed the ReturnPasswordHash value in the Authorization section from true to false. Set it to true if you use legacy vc-storefront.
https://virtocommerce.atlassian.net/browse/VCST-3430
Image tag:
ghcr.io/VirtoCommerce/platform:3.898.0-pr-2923-621c-vcst-3430-621cfb67

VCST-3430: Prevent auditable fields from modifications.

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/menu/mainMenu-item.tpl.html

fix: Adjust misaligned icons for News, Push Messages, and Tasks modules
https://virtocommerce.atlassian.net/browse/VCST-3738
Image tag:
ghcr.io/VirtoCommerce/platform:3.903.0-pr-2933-4658-vcst-3738-46586820

VCST-3738: Adjust misaligned icons for News, Push Messages, and Tasks modules

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/blades/role-detail.tpl.html

fix: Fix Duplicates in a repeater are not allowed error in role blade.
https://virtocommerce.atlassian.net/browse/VCST-3759
Image tag:
ghcr.io/VirtoCommerce/platform:3.903.0-pr-2934-6b90-vcst-3759-6b90184d

VCST-3759: Fix Duplicates in a repeater are not allowed

---

src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/blade/bladeNavigation.js

https://virtocommerce.atlassian.net/browse/VCST-1537
Image tag:
ghcr.io/VirtoCommerce/platform:3.904.0-pr-2937-aa77-vcst-1537-navigation-group-aa773054

VCST-1537: Support blades with the same ID within different navigation groups

---

src/VirtoCommerce.Platform.Security/CustomUserValidator.cs

fix: Enhanced validation message to include hyphen as an acceptable character.
https://virtocommerce.atlassian.net/browse/VCST-3844
Image tag:
ghcr.io/VirtoCommerce/platform:3.904.0-pr-2938-b2e6-vcst-3844-b2e62620

VCST-3844: Enhanced validation message to include hyphen as an acceptable character.
