VirtoCommerce/vc-platform

- azuredeploy.json
I've updated the ARM template in order to make it compatible with service principal (SPN) based authentication, which I use in Visual Studio Team Services to create VC Azure deployments. Without these changes, some weird authorization errors occur when the deployment is trying to update web.config, which tells me that the previous API version is not fully compatible with SPN.
The configuration updates are based on David Ebbo's ARM template sample found here:
https://github.com/davidebbo/AzureWebsitesSamples/blob/3ab2e9ff14c66719271a62c1ba8213c5258c7a6e/ARMTemplates/WebSiteManyFeatures.json
> Updated connection strings and appSettings configuration

- VirtoCommerce.Platform.Data.Azure/AzureBlobProvider.cs
We get an error in ImageTools module when trying to generate thumbnails for uploaded images. Azure CloudBlobClient does not work correctly when accessing the image via CDN Url. So, in this fix, we replace CDN Url with base storage Url when open blob for reading.
> Change URI when open blob for read using CDN

- VirtoCommerce.Platform.Data/Notifications/NotificationManager.cs
I created a new notification type that overrides the Order Paid Notification Email:
notificationManager.OverrideNotificationType(
() => new MoreOrderPaidEmail(memberService, _container.Resolve())
{
NotificationTemplate = new NotificationTemplate
{
Body = OrderPaid.MoreOrderPaidNotificationBody,
Subject = OrderPaid.MoreOrderPaidNotificationSubject
}
});
This means that in the virto front end: I can modify the MoreOrderPaidEmail but not the OrderPaidEmailNotification, as expected, but of course the NotificationTypeId is MoreOrderPaidEmail as well.
When the email is sent, triggered by the OrderNotificationObserver, it looks for a notification template OrderPaidEmailNotification, even when overriden, so it doesn't find the template.
I think this can be fixed as below, as we should use the …
> Fix retrieval of notification template for overriden notification.

- VirtoCommerce.Platform.Core/Notifications/INotificationManager.cs
- VirtoCommerce.Platform.Data/Notifications/NotificationManager.cs
Allows unregistering of notifications: for example when you don't want to send several mails while creating an order.
Related to https://github.com/VirtoCommerce/vc-module-order/pull/33
As discussed on Gitter: lots of changes are coming to the notification module, so this is a fix until that has been done. It will be better if 'IsActive' is actually used or there is another property to use for it, as that could then be used in the search notifications criteria. Right now, if you used to have a notification of a certain type, but it has been unregistered, it will show as an empty row in the notification history.. That could be fixed by using IsActive.
> Allow unregistering of notification types.

- VirtoCommerce.Platform.Core/Notifications/SearchNotificationCriteria.cs
- VirtoCommerce.Platform.Core/PushNotifications/PushNotificationSearchCriteria.cs
For fix issue [#7](https://github.com/VirtoCommerce/vc-module-cache/issues/7) in vc-platform all *SearchCriteria classes should realize method 'ICacheKey.GetCacheKey()' which implemented in ValueObject class.
Inherit all *SearchCriteria classes from ValueObject.
Nothing
> Update inheritance of *SearchCriteria classes.

- VirtoCommerce.Platform.Data/Assets/FileSystemBlobProvider.cs
- VirtoCommerce.Platform.Tests/Assets/BlobStorageProviderTests.cs
At now this method returns stream with ReadWrite permissions. Inspired by #845 
Fix 'File.Open()' params.
Nothing here.
> 'FileSystemBlobStorage.OpenRead()' should return read-only stream

- VirtoCommerce.Platform.Core/Common/ObjectExtension.cs
When trying to save `null` value for a dynamic property value of type `DateTime` the `null` value is converted to `0001-01-01T00:00:00.0000000`, which cannot be saved to the database.
Don't convert `null` to `default(T)`
> ToNullable should return null instead of default(T)

- VirtoCommerce.Platform.Web/Scripts/app/security/dialogs/changePasswordDialog.tpl.html
The password confirmation placeholder on the password change dialog was missing (I probably broke it while working on #1433). So this PR restores it.
(Sorry, looks like the `dev` branch is protected, so I don't have a permission to push this change directly to `dev`).
> 1433: added password confirmation placeholder on password change dialog

- VirtoCommerce.Platform.Web/Swagger/SwaggerConfig.cs
This PR is a part of the VirtoCommerce/vc-module-cart#28. It helps to solve Swagger validation errors like `$ref values must be RFC3986-compliant percent-encoded URIs` and contains a workaround for the way Swashbuckle handles generic types. Please see the comment in the code for explanation of why it was added and how it works.
P.S. I tried to use the `WebHelper.UrlEncode(...)` method instead of replaces - it seems to be a more correct solution. But it causes the Swagger Editor to fail to resolve any generic type references. So, `UrlEncode` probably can't be used here.
> CartModule, 28: Swagger JSON validation issues

- VirtoCommerce.Platform.Web/Scripts/app/settings/blades/settings-detail.tpl.html
This PR is a part of the AvaTax module refactoring. It adds the widget container to the settings detail blade (`settings-detail.tpl.html` template), so that the AvaTax module could insert the "Test connection with AvaTax" widget to its settings. This, in turn, will allow AvaTax module users to check their platform-wide AvaTax settings before saving them and potentially breaking the tax calculation.
> Added widget container to the settings detail blade

- VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
There was a reference in the `VirtoCommerce.Platform.Web` project that [referred to a library on my PC](https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj#L158):
I've probably added it by mistake while working on the issue #1388. The `Microsoft.IdentityModel.Protocols` library itself was not used by this project (it uses `System.IdentityModel.Tokens.Jwt` library instead), so this reference can be safely removed.
/cc @priboltik
> VirtoCommerce.Platform.Web: removed a reference with incorrect path

- VirtoCommerce.Platform.Web/Startup.cs
We can't use filters in AI Live Metrics because we have no API Key configured for that. We can't put it directly to applicationinsights.config because it's not secure & will cause problems on deployment.
Add code which allow you to specify this settings in app settings using special key.
1. Instruction from Microsoft: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-live-stream#secure-the-control-channel
2. Why different code used and what it mean (we don't want to reinitialize all processors because of that single simple task): https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/733#issuecomment-349752497
3. Why this name of key used (Microsoft has plans to have built-in mechanism to specify it in the future): …
> Application Insights Live Metrics: Secure the control channel

- VirtoCommerce.Platform.Web/Startup.cs
- VirtoCommerce.Platform.Web/Web.config
Need to have possibility switch the platform cache configuration to work with Redis server by change only one application setting (probably add connection Redis string).
Added a new setting in appSettings to control using of scaled up VC cache instances
- Added a new parameter `VirtoCommerce:Cache:ScaleUpEnabled` to appSettings
- Added new cache manager to switch
- Added checks to decide which cache manager should be chosen (default mem cache or scaled up within Redis) or create a default mem cache manager if nothing was found
> #1507 Added appSettings parameter to control using of VC cache instances

- VirtoCommerce.Platform.Tests/app.config
- VirtoCommerce.Platform.Web/ApplicationInsights.config
- VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
- VirtoCommerce.Platform.Web/Web.config
- VirtoCommerce.Platform.Web/packages.config
Memory leackage was related to bug that existe in AI of version 2.8.1. That version have critical bug https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1090. This error is not in the latest version of AI 2.9.1.
> Memory leak in vc-platform was eliminated

- VirtoCommerce.Platform.Web/Startup.cs
- VirtoCommerce.Platform.Web/Web.config
- Added "VirtoCommerce:Cache:Redis:ChannelName" option for specifying redis channel name different from default;
> #1582 Support using the same Redis server by multiple platform instances belonging to different tenants:

- VirtoCommerce.Platform.Web/Web.config
Default Outbound Network Connection Limit increased to 8064 to meet Standard S3 1 Instance connection limit: 8064
> #1594: Default Outbound Network Connection Limit increased to 8064

- VirtoCommerce.Platform.Web/Startup.cs
Motifvation for this PR is described in #1610. Now the platform will always have some implementation of the SMS gateway, so that:
1. If `VirtoCommerce:Notifications:SmsGateway` is set to `Default`, default SMS gateway will be used;
2. If `...SmsGateway` is set to `Twilio` or `ASPSMS`, the platform will instantiate, register and use that SMS provider;
3. If `...SmsGateway` is set to some value unknown by the platform and any of installed modules, default SMS gateway will be registered and used. This way, the platform will successfully start, but won't send any SMS notifications, because default SMS gateway can't do that.
4. If `...SmsGateway` value is unknown by the platform, but known by some installed module, then the platform will register default SMS gateway, and that module will then …
> 1610: registering default SMS gateway for any gateway name unknown by the platform

- build/Build.cs
dotnet pack ignores Version property because of GitVersionTask dependency
added property UpdateVersionProperties=false to vc-build's pack target
> Target Pack: added property UpdateVersionProperties for modules

- src/VirtoCommerce.Platform.Modules/Local/LocalStorageModuleCatalog.cs
This bug prevented platform modules from being copied to the module discovery folder on Mac and Linux
Platform modules need to be copied from the probe module folder to discovery folder
Remove the hard-coded backslash path separator: it's unneeded with Path.Combine and not valid on Mac and Linux
> fix: Bug on non-Windows systems using backslash

- VirtoCommerce.Platform.Data.Azure/AzureBlobProvider.cs
https://github.com/VirtoCommerce/vc-platform/issues/1760#?repos=60280313&search=1060
To avoid case with the wrong content type of the blob, when it 
uses  AzureBlobProvider for CMS content, better get content type
on a fly at BlobInfo returning.  The wrong type can be  formed 
when CMS data imported direct to Azure Blob Storage.
> Fix the error of the opening the content editing blade

- src/VirtoCommerce.Platform.Web/Startup.cs
Clearing the global default claim maps breaks claim mapping for azure ad
Backup token handling and pass that in as a parameter to open id connect options
Creating a new token handler before the maps are cleared will preserve default behavior.
> 1780: Preserve default token handler for Azure AD

- src/VirtoCommerce.Platform.Core/Security/ClaimsPrincipalExtensions.cs
security:api_call permission is required
How it working on v2:
https://github.com/VirtoCommerce/vc-platform/blob/414fd969bfa1568f294c1d302b985ab308ba4058/VirtoCommerce.Platform.Data.Security/SecurityService.cs#L474-L479
This permission isn't required
If user has type manager or administrator and checking permission is security:api_call, then allow action
> Fixed problem with security:api_call permission checking

- VirtoCommerce.Platform.Core/Notifications/SearchNotificationCriteria.cs
- VirtoCommerce.Platform.Data/Notifications/NotificationManager.cs
- VirtoCommerce.Platform.Web/BackgroundJobs/SendNotificationsJobs.cs
- VirtoCommerce.Platform.Web/Startup.cs
At the moment retry interval for failed notifications is 5 hours by default and there is no possibility to change it.
Add ability to set in admin panel retry interval for resending failed notifications.
Add new parameter for retry interval that can be changed in module settings.
> Added retry interval setting for failed notifications.

- src/VirtoCommerce.Platform.Web/appsettings.json
Changed the way to launch Hangfire. By default SqlServer mode should be used instead of MemoryStorage
> Added a setting for running Hangfire in SqlServer mode (instead of MemoryStorage)

- VirtoCommerce.Platform.Web/Web.config
When application runs with IIS. There is unable to make request with symbol "+" into the route
Here solution and explanation
https://stackoverflow.com/questions/1453218/is-enabling-double-escaping-dangerous
Allow double escaping
> VP-2309: [BUG] Using + in User name

- src/VirtoCommerce.Platform.Web/Security/CustomUserManager.cs
Need to revert as this change results in very long import of sample data, probably because of multiple calls of the overridden method.
> VP-2538: Revert "VP-2538: Fix error on lock out"

- .github/workflows/main.yml
Docker images with SHA as a tag are not useful.
Use [version number]-[sha (first 8 chars)] if version suffix is not defined or
[version number]-[version suffix]-[sha (first 8 chars)].
Read Version and Suffix from Directory.Build.Props
N/A
> VP-2794: Start using short sha

- .github/workflows/delivery.yml
The Deploy workflow required ARGO CD token.
Get rid of forcing sync operation since sync happens on push to the VirtoCommerce/vc-deploy-apps repository.
N/A
N/A
> VP-3273: Get rid of forcing sync operation

- CommonAssemblyInfo.cs
- VirtoCommerce.Platform.Data.Notifications/SendGridEmailNotificationSendingGateway.cs
- VirtoCommerce.Platform.Data/Notifications/DefaultSmtpEmailNotificationSendingGateway.cs
The start sending date is always today's date and time when notification was successfully sent via smtp. 
This date should be date/time when send process started. 
It was null all the time, so i added assignment to the corresponding property.
> VP-3329: Set Start sending date for new email notifications

- .github/workflows/main.yml
After renaming `storefront-core` to `storefront` CI workflow failed in swagger validation job because it uses шьфпуы шт docker.pkg.github.com/virtocommerce/vc-storefront-core/storefront 
Fix path to storefront repository in main.yml
> Fix path to storefront repository in main.yml

- .github/workflows/main.yml
Set VirtoCommerce/vc-github-actions/get-image-version to master branch
> Fix get image version action

- .github/workflows/main.yml
CI fails after Directory.Build.props renaming
Remove  `mv Directory.Build.Props Directory.Build.props`  from CI
> VP-4159: Fix CI fail

- src/VirtoCommerce.Platform.Security/Migrations/20000000000000_UpdateSecurityV2.cs
Simple API keys upgrade copying was forgotten to implement.
> VP-5190: Add copying simple API keys during v2-v3 migration

- src/VirtoCommerce.Platform.Web/Swagger/SwaggerServiceCollectionExtensions.cs
- src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
Currently, there is no way to expose derived types in Swagger API description. For example, consider the following code:
```csharp
// Models definition in ...Core assembly
public abstract class BaseObject
{
// ...
}
public class DerivedObject : BaseObject
{
// ...
}
public class AnotherDerivedObject : BaseObject
{
// ...
}
// Controller method that returns these models
public ActionResult<IList<BaseObject>> GetObjects()
{
var result = new[] 
{
new DerivedObject(),
new AnotherDerivedObject()
};
return Ok(result);
}
```
In this example, only the `BaseObject` will be exposed in Swagger. `DerivedObject` and `AnotherDerivedObject` will be missing from JSON with API definition, and the only way to expose them is to add some other API method that will explicitly accept or return any of these …
> HDOT-1743 Allow to expose polymorphic types in Swagger API

- src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs
- src/VirtoCommerce.Platform.Web/Extensions/ServiceCollectionExtensions.cs
Application parts for modules with loading errors should not be added, as such modules could break our application - as their types could not be loaded in runtime. Added such filtration in startup
> VP-2190: Do not add application parts for failed modules

- src/VirtoCommerce.Platform.Core/Settings/ObjectSettingEntry.cs
- src/VirtoCommerce.Platform.Core/Settings/SettingsExtension.cs
They still could be got via the extended version of `ISettingsManager.DeepLoadSettingsAsync`
> VP-5722: Do not return hidden settings for entities by default

- src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_errors.sass
- src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/dialogs/errorDetails-dialog.tpl.html
VP-5983 Error popup > text is too long and appears outside of popup
When we try to make Bulk Update for Cell Phones category then an error popup appears with long text (it works ok for other categories).
Fix markup to show long error message
Add error scrolling 
Add error word wrap
> Fix markup to show long error message

- src/VirtoCommerce.Platform.Web/Startup.cs
[11/10 9:26 AM] Egidijus Mazeika
Hey, I've got an issue that platform permissions are missing at module postInitialize time. It's a bug in https://github.com/VirtoCommerce/vc-platform/blob/9c794c511ddb6afb9f167787a7572a2aabdecd82/src/VirtoCommerce.Platform.Web/Startup.cs#L513-L516 and the fix is to switch those 2 lines.
​
​[3:40 PM] Eugeny Tatarincev
I think it is absolutely safe to swap them
> VP-0: Ensure platform permissions are present at module postInitialization time

- src/VirtoCommerce.Platform.Web/Controllers/Api/ChangeLogController.cs
This PR adds an endpoint which invalidates `GlobalCacheRegion` - this will purge the entire platform cache. It might be useful to reset cache after database changes by platform administrators (via direct SQL scripts) or to investigate cache issues by platform developers.
Note: I intentionally did not add this endpoint to platform UI - it should only be used when it's absolutely needed, so platform administrators MUST know why they need to reset the cache to use this endpoint. That's why IMO there should be no easy way to do it from UI.
> Allow to reset platform cache via endpoint call

- src/VirtoCommerce.Platform.Core/PlatformConstants.cs
VP-6462 platform:security:loginOnBehalf permission is missing
https://github.com/VirtoCommerce/vc-platform/issues/2118
The Login on behalf button is bound to the platform:security:loginOnBehalf permission, but this permission is not present in the permissions list and it cannot be assigned to any role
Add security constant to platform
> VP-6462: Platform:security:loginOnBehalf permission is missing

- src/VirtoCommerce.Platform.Core/Common/ValueObject.cs
- tests/VirtoCommerce.Platform.Tests/UnitTests/ValueObjectUnitTests.cs
This PR fixes the following issues that lead to incorrect equality components and duplicate cache keys:
1. `null` and `"null"` values are considered equal.
2. Empty collections are just ignored.
> ValueObjects with different values should not be equal and should have different cache keys

- docs/techniques/authentication-with-azure-ad.md
- src/VirtoCommerce.Platform.Web/Azure/AzureAdOptions.cs
- src/VirtoCommerce.Platform.Web/Controllers/ExternalSignInController.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
- src/VirtoCommerce.Platform.Web/appsettings.json
If your app has custom signing keys you can receive this error on `POST https://localhost:5001/signin-oidc` request.
```json
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key
```
https://github.com/Azure/azure-sdk-for-net/issues/17695
If your app has custom signing keys as a result of using the claims-mapping feature, you must append an appid query parameter containing the app ID in order to get a jwks_uri pointing to your app's signing key information. For example: https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration?appid=6731de76-14a6-49ae-97bc-6eba6914391e contains a jwks_uri of https://login.microsoftonline.com/{tenant}/discovery/v2.0/keys?appid=6731de76-14a6-49ae-97bc-6eba6 …
> VP-6484: Fix SSO Azure AD  signature validation failed error when Azure AD App has custom signing keys

- src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
Regenerate SecurityStamp on email change:
* This will expire any previous token (incl. email confirmation token)
Define ApplicationDiscriminator:
* When the same ApplicationDiscriminator used in Storefront and Platform, the Identity UserManager can validate tokens issued in both applications.
Jira: https://virtocommerce.atlassian.net/browse/VP-6894
> VP-6894: Regenerate SecurityStamp on email change; Define ApplicationDiscriminator

- src/VirtoCommerce.Platform.Core/Modularity/IHasConfiguration.cs
- src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs
added IHasConfiguration interface so that we could use IConfiguration in module initialize without calling BuildServiceProvider
https://virtocommerce.atlassian.net/browse/VP-6905
> VP-6905 add IHasConfiguration interface

- src/VirtoCommerce.Platform.Web/Startup.cs
This allows to configure token lifespan for data protection options in appsettings.json:
https://virtocommerce.atlassian.net/browse/PT-986
> PT-986: Add ability to configure DataProtection options

- src/VirtoCommerce.Platform.Assets.AzureBlobStorage/AzureBlobProvider.cs
- src/VirtoCommerce.Platform.Assets.AzureBlobStorage/FlushLessStream.cs
Typically, we use MemoryStream to prevent multiple flushes to BlockBlobWriteStream, otherwise, the stream write hangs.
Another side of this approach is redundant memory consumption, even "out of memory" errors.
The solution is to wrap BlockBlobWriteStream and call the Flush for it only once at the Dispose. This allows removing all redundant MemoryStream copies in using places (a.e. exports).
https://github.com/Azure/azure-sdk-for-net/issues/20652
https://virtocommerce.atlassian.net/browse/PT-1910
https://virtocommerce.atlassian.net/browse/PT-3876
> PT-3877: Add FlushLessStream, a workaround to avoid hangs on writing to AzureStorage

- src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs
- src/VirtoCommerce.Platform.Web/Swagger/OpenIDEndpointDescriptionFilter.cs
- src/VirtoCommerce.Platform.Web/Swagger/SwaggerServiceCollectionExtensions.cs
There wasn't a description for OAuth token request endpoint:
Now it's up and running for the test:
https://virtocommerce.atlassian.net/browse/PT-3801
> PT-3802: Add swagger description for OAuth token request endpoint

- src/VirtoCommerce.Platform.Data/ExportImport/JsonSerializerExtensions.cs
The issue was discovered incidentally. While importing store tax providers DB threw an error with problems with a unique index. I started to research and found that some of our entities use discriminators for typecasting. And tax provider is one of that entities, so that while importing we should just call generic  Newtonsoft's deserializer method, and our Polymorphic JSON converter will cast the right type for us.
> Fix type casting while deserealization

- src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/breadcrumbs/breadcrumbs.js
This bug is "phantom" and hard to reproduce.
But there is no point in having active "Back" button when you reopen the same blade once again => let's reset the history every time when the blade is reopened.
> PT-692: Clear blade history every time when the same blade is reopened

- src/VirtoCommerce.Platform.Web/wwwroot/js/app/systemInfo/blades/system-info.tpl.html
Fixed wrong value for License Type on platform information blade, if the license is activated. From  "license, expires on Oct 4, 2021",  To correct, Ex: Cloud.
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Platform.3.83.0-pr-2387.zip
> Fixed misspeling

- src/VirtoCommerce.Platform.Core/Extensions/StringExtensions.cs
Fix an error in the absolute URI checker
Folder names starting from the same letters as protocol names now acceptable.
https://virtocommerce.atlassian.net/browse/PT-4531
> PT-4531: Fix an error in absolute URI checker

- src/VirtoCommerce.Platform.Core/PlatformOptions.cs
Resolved issue with app_data in the path and 404 error on Azure Envirionent when download export document.
Client see 400 or 404 error because "_" is prohobiten symbol. 
Client see 400 or 404 error because "_" is prohobiten symbol.
> app_data and 404

- src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
This PR modifies the `CrudService.SaveChangesAsync()` method to allow customization of loading existing entities and finding the matching one for each model being saved. Currently, this is always done by ID, and the only way to customize this behavior is to override the entire `SaveChangesAsync()` method. However, this PR extracts these operations into separate methods, providing a simpler way for such customization.
Imagine some hypothetical service that deals with some entities like product tags.
```csharp
// Transient model in ...Core/Models
public class Tag : AuditableEntity
{
public string TaggedItemId { get; set; }
public string Tag { get; set; }
}
// Persistable entity in ...Data/Models
public class TagEntity : AuditableEntity, IDataEntity<TagEntity, Tag>
{
[Required] …
```
> CrudService.SaveChangesAsync(): Customize loading and matching existing entities

- src/VirtoCommerce.Platform.Core/Caching/MemoryCacheExtensions.cs
- src/VirtoCommerce.Platform.Core/Extensions/DictionaryExtension.cs
- src/VirtoCommerce.Platform.Core/Extensions/EnumerableExtensions.cs
- src/VirtoCommerce.Platform.Core/Extensions/ObjectExtension.cs
- src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
When calling `GetAsync("1", "2")` and then `GetAsync("2", "1")` or `GetAsync("1")`, CrudService loads the same objects from the database multiple times and adds the same objects to the cache multiple times because it builds the cache key by joining all ids into a single string.
Build a separate cache key for each object and add only one object per id to the cache.
- Reduced number of requests to the database
- Reduced memory usage
> Optimize caching in CrudService

- .github/workflows/codeql-analysis.yml
- src/VirtoCommerce.Platform.Core/Common/ReflectionUtility.cs
- tests/VirtoCommerce.Platform.Core.Tests/Common/ReflectionUtilityTests.cs
New implementation significantly reduces CPU and memory usage.
There are two main changes:
- Use HashSet to detect reference loops
- Don't create intermediate lists and arrays when making recursive calls
Benchmark results for a smallest entity `CommandBase`: 3 times faster, 5 times less allocated memory:
```
| Method |       Mean |    Error |   StdDev |  Gen 0 | Allocated |
|------- |-----------:|---------:|---------:|-------:|----------:|
|    Old | 3,305.9 ns | 40.85 ns | 38.21 ns | 0.4959 |   2,089 B |
|    New |   923.9 ns |  5.68 ns |  5.03 ns | 0.1011 |     424 B |
```
Benchmark results for a large entity `ExtendedCustomerOrderAggregate` with about 13000 nested entities: **19 times faster**, 2.5 times less allocated memory:
```
| Method |        Mean |    Error |   StdDev |     Gen …
```
> Improve performance of GetFlatObjectsListWithInterface()

- .github/CODEOWNERS
Added GitHub Codeowners
GitHub Codeowners feature allow automating PR Reviewers assign
https://github.blog/2017-07-06-introducing-code-owners/
> feat: add codeowners feature

- VirtoCommerce.Platform.sln
- src/VirtoCommerce.Platform.Caching/GenericCachingRegion.cs
When calling `GenericCachingRegion.CreateChangeToken(products)` the following error occurs:
```
System.InvalidCastException: Unable to cast object of type
'SelectEnumerableIterator`2[VirtoCommerce.CatalogModule.Core.Model.CatalogProduct,System.String]' to type
'System.Collections.Generic.IEnumerable`1[VirtoCommerce.CatalogModule.Core.Model.CatalogProduct]'.
```
> Fix InvalidCastException

- src/VirtoCommerce.Platform.Core/Settings/ObjectSettingEntry.cs
- src/VirtoCommerce.Platform.Data/Settings/SettingsManager.cs
Make `OldEntry` and `NewEntry` in `ObjectSettingChangedEvent` consistent and prevent false changes in audit log.
https://virtocommerce.atlassian.net/browse/PT-8404
> PT-8404 Fill setting properties from the descriptor when publishing ObjectSettingChangedEvent

- .editorconfig
- .gitignore
- .nuke
- VirtoCommerce.Platform.sln.DotSettings
- src/VirtoCommerce.Platform.Core/Json/OutputJsonSerializerSettings.cs
- src/VirtoCommerce.Platform.Web/Json/ConfigureMvcOptions.cs
- src/VirtoCommerce.Platform.Web/Json/ConfigureOutputJsonSerializerSettings.cs
- src/VirtoCommerce.Platform.Web/Json/MvcBuilderExtensions.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
A hamburger menu in a grid contains only those fields, that are present in the very first record in the grid.
This PR makes all fields to be serialized even if its values are `null`.
https://virtocommerce.atlassian.net/browse/PT-8520
> PT-8520: New fields not showing up in hamburger menu

- src/VirtoCommerce.Platform.Caching/PlatformMemoryCache.cs
the 3rd party code could call GetDefaultCacheEntryOption without AddExpirationToken and items can be in InMemory cache if redis is disconned.
> PT-8727 Moved AddExpirationToken to GetDefaultCacheEntryOption

- src/VirtoCommerce.Platform.Security/Services/ServerCertificateService.cs
Remove redundant Oids in self-signed certificate generator to improve compatibility with MacOS.
Seems we can skip additional oids because we use certs in bearer auth only.
https://virtocommerce.atlassian.net/browse/PT-8963
> PT-8963: Remove redundant Oids in self-signed certificate generator (MacOS compatible)

- src/VirtoCommerce.Platform.Security/CustomIdentityError.cs
- src/VirtoCommerce.Platform.Security/CustomIdentityErrorDescriber.cs
- tests/VirtoCommerce.Platform.Web.Tests/Security/CustomPasswordValidatorTests.cs
Store identity error value as a separate error parameter allowing to propagate error details separately from the error description
https://virtocommerce.atlassian.net/browse/PT-9132
> PT-9132: Store identity error value as a separate error parameter

- src/VirtoCommerce.Platform.Caching/VirtoCommerce.Platform.Caching.csproj
- src/VirtoCommerce.Platform.DistributedLock/VirtoCommerce.Platform.DistributedLock.csproj
feat: Update StackExchange.Redis From 2.1. To 2.6.86.  [ReleaseNotes](https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes), [Configuration](https://stackexchange.github.io/StackExchange.Redis/Configuration)
> PT-9049: Update StackExchange.Redis From 2.1. To 2.6.86

- src/VirtoCommerce.Platform.Core/Exceptions/SettingsTypeNotRegisteredException.cs
- src/VirtoCommerce.Platform.Core/Settings/SettingsExtension.cs
https://virtocommerce.atlassian.net/browse/PT-10515
> PT-10515: Fix no settings exception, SettingsTypeNotRegisteredException obsolete

- src/VirtoCommerce.Platform.Web/Startup.cs
fix: move  AI telemetry in the end of ConfigureServices method in order to avoid of multiple AI modules initialization.
> PT-10998: move  AI telemetry in the end of ConfigureServices method

- src/VirtoCommerce.Platform.Web/Swagger/SwaggerServiceCollectionExtensions.cs
feat: Add YAML support for OpenAPI 3 and Swagger UI. Both formats are supported. Use swagger.json or swagger.yaml.
> PT-11548: Add YAML support for OpenAPI 3 and Swagger UI. 

- src/VirtoCommerce.Platform.Data.PostgreSql/PostgreSqlCertificateLoader.cs
Sql commands to load the certificate are not correct for postgresql.
Fixed the command to check the presence of ServerCertificate table and the command to load the certificate.
Verified with PostgreSQL 15.2
Without this fix the number of rows in ServerCertificate table is incremented each time the application is restarted
> fixed posgresql commands to load the certificate

- src/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs
Both DateTime.MaxValue and DateTime.MinValue has Unspecified kind. There's an error when trying to save such a value to PostgreSql database.
This fix converts the dates into the universal time and "Lock account" works ok.
It was verified with PostgreSQL 15.2 and MySql 5.7 versions (Security/Users/account Lock account command)
> fix for lock user account when db provider is PostreSql

- src/VirtoCommerce.Platform.Core/Modularity/ManifestModuleInfo.cs
- src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs
https://virtocommerce.atlassian.net/browse/PT-12095
> PT-12095: Use moduleType specified in the manifest

- src/VirtoCommerce.Platform.Core/Security/Events/UserPasswordChangedEvent.cs
- src/VirtoCommerce.Platform.Core/Security/Events/UserResetPasswordEvent.cs
- src/VirtoCommerce.Platform.Security/CustomUserManager.cs
https://virtocommerce.atlassian.net/browse/PT-12140
> PT-12140: Fix ResetPasswordAsync and ChangePasswordAsync

- src/VirtoCommerce.Platform.Core/Security/AuthorizationOptions.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
- src/VirtoCommerce.Platform.Web/appsettings.json
feat: Add "AllowApiAccessForCustomers" setting. Enables or disables API access for customers.  By default, false. When set to true, it allows customers to access the API endpoints and perform authorized actions. 
App settings section: Authorization:AllowApiAccessForCustomers.
```json
"Authorization": {
...
"AllowApiAccessForCustomers": true,
...
},
```
> PT-12153: Add "AllowApiAccessForCustomers" setting. 

- src/VirtoCommerce.Platform.Web/npm-shrinkwrap.json
- src/VirtoCommerce.Platform.Web/package.json
fix: Bump jQuery from 2.1.4 to 3.7.0
> PT-12552: Bump jQuery from 2.1.4 to 3.7.0

- src/VirtoCommerce.Platform.Hangfire/Extensions/ServiceCollectionExtensions.cs
Hangfire fire exception if there is no already created database when use PostreSql because of missed workaround already available for MySql and SqlServer.
> VM-1179: Fix exception if no database already created in PostgreSql

- src/VirtoCommerce.Platform.Web/Extensions/ApplicationBuilderExtensions.cs
- src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
feat: Adds the following security headers to all responses:
* X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains - only applied to HTTPS responses
* X-Frame-Options: Deny - only applied to "document" responses
* X-XSS-Protection: 1; mode=block - only applied to "document" responses
* Referrer-Policy: strict-origin-when-cross-origin - only applied to "document" responses
* Content-Security-Policy: object-src 'none'; form-action 'self'; frame-ancestors 'none' - only applied to "document" responses
by using https://github.com/andrewlock/NetEscapades.AspNetCore.SecurityHeaders
> PT-10550: adds the security headers to all responses

- src/VirtoCommerce.Platform.Security/ExternalSignin/ExternalSignInProviderConfiguration.cs
- src/VirtoCommerce.Platform.Web/Controllers/ExternalSignInController.cs
- src/VirtoCommerce.Platform.Web/Model/Security/ExternalSignInProviderInfo.cs
- src/VirtoCommerce.Platform.Web/wwwroot/js/app/security/login/login.tpl.html
> PT-13784: Add logoUrl

- src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
fix: Could not load file or assembly Azure.Messaging.EventGrid, Version=4.11.0.0 after 3.424.0 release.
> PT-13986: Could not load file or assembly Azure.Messaging.EventGrid

- src/VirtoCommerce.Platform.Core/Exceptions/InvalidCollectionItemException.cs
- src/VirtoCommerce.Platform.Data.MySql/Migrations/Data/20231026084751_DynamicPropertyItemNameRequired.Designer.cs
- src/VirtoCommerce.Platform.Data.MySql/Migrations/Data/20231026084751_DynamicPropertyItemNameRequired.cs
- src/VirtoCommerce.Platform.Data.MySql/Migrations/Data/PlatformDbContextModelSnapshot.cs
- src/VirtoCommerce.Platform.Data.MySql/Readme.md
- src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Data/20231026085000_DynamicPropertyItemNameRequired.Designer.cs
- src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Data/20231026085000_DynamicPropertyItemNameRequired.cs
- src/VirtoCommerce.Platform.Data.PostgreSql/Migrations/Data/PlatformDbContextModelSnapshot.cs
- src/VirtoCommerce.Platform.Data.PostgreSql/Readme.md
- src/VirtoCommerce.Platform.Data.SqlServer/Migrations/Data/20231026083345_DynamicPropertyItemNameRequired.Designer.cs
- src/VirtoCommerce.Platform.Data.SqlServer/Migrations/Data/20231026083345_DynamicPropertyItemNameRequired.cs
- src/VirtoCommerce.Platform.Data.SqlServer/Readme.md
- src/VirtoCommerce.Platform.Data/DynamicProperties/DynamicPropertyDictionaryItemsService.cs
- src/VirtoCommerce.Platform.Data/Model/DynamicPropertyDictionaryItemEntity.cs
- src/VirtoCommerce.Platform.Web/Controllers/Api/DynamicPropertiesController.cs
fix: Dynamic dictionary item name must be required. Throw InvalidCollectionItemException if One or more items in the collection have a null or empty Name. API returns BadRequest. 
fix: Fixs Name can be null or empty in DB. The update marks DynamicPropertyDictionaryItemEntity Name as required. Name with either Null or Empty value will be converted to unique id automatically.
> PT-13884: Dynamic dictionary item name must be required.

- src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/genericValueInput.js
We've run into a rare bug where some of our organization objects did not display full list of available dictionary items for one of the dynamic properties in the management -> _Dynamic properties_ blade. The dropdown had just the first item. This turned out to happen when the API sent a value object with `valueType` of `Undefined` and no actual `value` property, something like this:
```json
{
...
"dynamicProperties": [
{
"values": [
{
"objectType": "VirtoCommerce.CustomerModule.Core.Model.Organization",
"objectId": "1234",
"valueId": "xyz",
"valueType": "Undefined",
"propertyId": "MyCustomObject_VirtoCommerce.Domain.Customer.Model.Organization",
"propertyName": "MyCustomObject"
}
],
...
}
],
...
}
```
We don't know why the value was like that (maybe a side effect of migrating from VC 2), …
> Fix a bug where the dropdown with available dictionary items has only the first item

- Directory.Build.props
- src/VirtoCommerce.Platform.Data.SqlServer/VirtoCommerce.Platform.Data.SqlServer.csproj
- src/VirtoCommerce.Platform.Hangfire/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.Platform.Hangfire/VirtoCommerce.Platform.Hangfire.csproj
- src/VirtoCommerce.Platform.Web/Security/ApplicationBuilderExtensions.cs
- src/VirtoCommerce.Platform.Web/appsettings.json
feat: [Update Hangfire to 1.8.0](https://www.hangfire.io/blog/2023/04/28/hangfire-1.8.0.html). It offers a set of great new features like first-class queue support for background jobs, the enhanced role of the Deleted state that now supports exceptions, more options for continuations to implement even try/catch/finally semantics, better defaults to simplify the initial configuration and various Dashboard UI improvements.
feat: Bump Hangfire to 1.8.6,  Hangfire.AspNetCore to 1.8.6, Hangfire.MemoryStorage to 1.8.0 , Hangfire.PostgreSql to 1.20.4 and HangFire.SqlServer to 1.8.6.
feat: Added  Hangfire:SqlServerStorageOptions:InactiveStateExpirationTimeout. It cleans up the old state entries of a non-finished job when InactiveStateExpirationTimeout is set. By default, 7 days.
> PT-14600: Update hangfire to 1.8.6

- src/VirtoCommerce.Platform.Web/Controllers/Api/SettingController.cs
use platform:setting:read permission to restrict endpoint GetGlobalSetting
> VCST-275: set correct permission to get global settings

- src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/smartFloat.js
fix: Incorrect validation for decimal fields in settings if value is empty string.
After the fix:
> VCST-410: Incorrect validation for decimal fields in settings

- src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
feat: Bump Microsoft.Bcl.AsyncInterfaces to 8.0.0
> VCST-565: Bump Microsoft.Bcl.AsyncInterfaces to 8.0.0

- src/VirtoCommerce.Platform.Caching/PlatformMemoryCache.cs
- src/VirtoCommerce.Platform.Core/Bus/HandlerWrapper.cs
- src/VirtoCommerce.Platform.Core/Bus/IHandlerRegistrar.cs
- src/VirtoCommerce.Platform.Core/Bus/InProcessBus.cs
- src/VirtoCommerce.Platform.Core/Events/ApplicationBuilderExtensions.cs
- src/VirtoCommerce.Platform.Core/Events/EventSuppressor.cs
- src/VirtoCommerce.Platform.Core/Events/IEventHandlerRegistrar.cs
- src/VirtoCommerce.Platform.Core/Events/IEventPublisher.cs
- src/VirtoCommerce.Platform.Data/ExportImport/PlatformExportImportManager.cs
- src/VirtoCommerce.Platform.Data/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.Platform.Hangfire/Extensions/ApplicationBuilderExtensions.cs
- src/VirtoCommerce.Platform.Web/Security/ApplicationBuilderExtensions.cs
- src/VirtoCommerce.Platform.Web/Security/ServiceCollectionExtensions.cs
- tests/VirtoCommerce.Platform.Tests/Common/CountriesServiceTests.cs
- tests/VirtoCommerce.Platform.Tests/Events/EventHandlerTests.cs
- tests/VirtoCommerce.Platform.Tests/Events/EventSuppressorTests.cs
```csharp
var handlerRegistrar = appBuilder.ApplicationServices.GetService<IHandlerRegistrar>();
handlerRegistrar.RegisterHandler<UserChangedEvent>(async (message, token) => await appBuilder.ApplicationServices.GetService<LogChangesUserChangedEventHandler>().Handle(message));
```
```csharp
appBuilder.RegisterEventHandler<UserChangedEvent, LogChangesUserChangedEventHandler>();
```
Also, now it's possible to register a handler for all event types:
```csharp
appBuilder.RegisterEventHandler<DomainEvent, AllEventsHandler>();
```
> [!Note]
> If you register an event handler for UserChangedEvent, this handler will receive UserChangedEvent and all events derived from UserChangedEvent.
https://virtocommerce.atlassian.net/browse/VCST-430
> VCST-430: Simplify event handlers registration

- src/VirtoCommerce.Platform.Core/Security/Events/UserChangedPasswordEvent.cs
- src/VirtoCommerce.Platform.Core/Security/Events/UserPasswordChangedEvent.cs
- src/VirtoCommerce.Platform.Core/Security/Events/UserResetPasswordEvent.cs
- src/VirtoCommerce.Platform.Security/CustomUserManager.cs
- src/VirtoCommerce.Platform.Security/Handlers/LogChangesUserChangedEventHandler.cs
- src/VirtoCommerce.Platform.Web/Security/ApplicationBuilderExtensions.cs
- tests/VirtoCommerce.Platform.Web.Tests/Security/CustomUserManagerEventsUnitTests.cs
- tests/VirtoCommerce.Platform.Web.Tests/Security/SecurityMockHelper.cs
Previously, when a user changed their password, the platform would publish the `UserPasswordChangedEvent` event twice: once for the operation itself, and once for the detected changes to the user properties.
This PR introduces a separate event for the `change password` operation - the `UserChangedPasswordEvent`.
So, now there are three events related to the password change:
- `UserResetPasswordEvent` - user has reset their password
- `UserChangedPasswordEvent` - user has changed their password
- `UserPasswordChangedEvent` - password has been changed for whatever reason. This event is published for both `reset password` and `change password` operations.
https://virtocommerce.atlassian.net/browse/VCST-781
> VCST-781: Publish two different events when changing password

- src/VirtoCommerce.Platform.Core/PlatformConstants.cs
- src/VirtoCommerce.Platform.Security/HttpContextUserResolver.cs
- src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs
- src/VirtoCommerce.Platform.Web/Extensions/OpenIddictExtensions.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
- src/VirtoCommerce.Platform.Web/Swagger/OpenIDEndpointDescriptionFilter.cs
feat: Adds the capability to perform login-on-behalf (impersonation) using token authentication within the XAPI framework. The new feature extends the /connect/token flow by adding support for a custom grant type called impersonate. Users can now leverage the grant_type=impersonate&user_id={user_id} parameter to set the vc_xapi_impersonated_customerid for impersonation purposes. Ensure that the account initiating the impersonation has the necessary platform:security:loginOnBehalf permission. To reset the impersonation , use the grant_type=impersonate and empty user_id.
> VCST-1047: login-on-begalf for token auth

- src/VirtoCommerce.Platform.Web/Swagger/CustomSwaggerGenerator.cs
* remove class field which stored a documentName for current schema generator
* reformat code
> VCST-822: fix swagger schemaId generator  for documentType

- src/VirtoCommerce.Platform.Core/Extensions/StringExtensions.cs
- src/VirtoCommerce.Platform.Web/Security/SecurityHeadersOptions.cs
- src/VirtoCommerce.Platform.Web/Security/ServiceCollectionExtensions.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
- src/VirtoCommerce.Platform.Web/appsettings.json
feat: Adds SecurityHeaders configuration to configure iframe security policy.
appsettings.json
```json
"SecurityHeaders": {
// X-Frame-Options header configuration. Allowed values: Deny - default, SameOrigin, or custom uri.
"FrameOptions": "Deny",
// FrameAncestors configuration in Content-Security-Header header. Allowed values: None - default, Self, or custom uri.
"FrameAncestors": "None"
},
```
https://virtocommerce.atlassian.net/browse/VCST-1128
> VCST-1128: Add Configuration for iframe security policy

- src/VirtoCommerce.Platform.Data.PostgreSql/VirtoCommerce.Platform.Data.PostgreSql.csproj
- src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
fix: Bump Microsoft.Identity.Client to 4.61.0, Npgsql to 8.0.3 and Npgsql.EntityFrameworkCore.PostgreSQL to 8.0.2.
Image tag:
3.825.0-pr-2792-8478-vcst-1209-bump-npgsql-8478bff6
> VCST-1209: Bump Microsoft.Identity.Client and Npgsql to latest version.

- src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj
feat: Bump Azure.Core  to 1.37.0 and Azure.Messaging.EventGrid to 4.22 to fit MS modules dependencies that use Azure.Core  to 1.37.0
Image tag:
3.826.0-pr-2794-6c10-vcst-1125-azure-core-1-37-6c109f27
> VCST-1125: Bump Azure.Core and Azure.Messaging.EventGrid

- src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/module-detail.js
- src/VirtoCommerce.Platform.Web/wwwroot/js/app/modularity/blades/module-detail.tpl.html
Image tag:
3.827.0-pr-2793-00a8-vcst-1213-00a8ee69
> VCST-1213: make optional dependencies inactive if no module info is found

- .github/workflows/platfotm-owasp.yml
Used latest version of GH action `zaproxy/action-baseline`, removed `docker_name` option as by default the action runs the stable version of ZAP.
https://github.com/zaproxy/action-baseline/blob/master/README.md#docker_name
https://virtocommerce.atlassian.net/browse/VCST-1107
> VCST-1107: Use latest zaproxy/action-baseline

- src/VirtoCommerce.Platform.Data/Repositories/PlatformRepository.cs
- src/VirtoCommerce.Platform.Data/Settings/SettingsManager.cs
- src/VirtoCommerce.Platform.Security/Services/UserSearchService.cs
- src/VirtoCommerce.Platform.Web/Controllers/Api/AppsController.cs
- src/VirtoCommerce.Platform.Web/Licensing/LicenseProvider.cs
fix: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
feat: Enables AsSplitQuery policy for queries. This behavior can improve performance when the query ApplicationUser, Settings and Dynamic Properties.
Image tag:
3.837.0-pr-2804-b0ea-vcst-846-b0eaa4a9
> VCST-846: Fix QuerySplittingBehavior.SingleQuery Warning in Platform

- src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/metaform.js
Added the ability to unregister meta fields by `name`, `templateUrl` or a custom search predicate callback
We originally did that in a custom module of ours, and @EugeneOkhriemnko suggested I create a PR here so everyone can benefit. 
Since there is no real method overloading in js, I did some `_.isFunction` magic to allow the same method ~group to accept the 3 different types of values for `metaFieldToFind`: name, function callback or object reference.
I added an error message because I think it's better t have an error than to silently not remove a field, but that could be considered a breaking change since the previous code didn't throw an error, if preferred this could be changed so that it only throws on error if `metaFieldDescription`, or not throw at all, or having this error …
> Improving unregistering metafields in metaforms.js

- src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/metaform.js
Original PR by @SamBauwensPM: https://github.com/VirtoCommerce/vc-platform/pull/2812
Added the ability to unregister meta fields by `name`, `templateUrl` or a custom search predicate callback
We originally did that in a custom module of ours, and @EugeneOkhriemnko suggested I create a PR here so everyone can benefit. 
Since there is no real method overloading in js, I did some `_.isFunction` magic to allow the same method ~group to accept the 3 different types of values for `metaFieldToFind`: name, function callback or object reference.
I added an error message because I think it's better t have an error than to silently not remove a field, but that could be considered a breaking change since the previous code didn't throw an error, if preferred this could be changed so that it only …
> VCST-1448: Added the ability to unregister meta fields by name, templateUrl or a custom search predicate callback.

- src/VirtoCommerce.Platform.Core/Domain/IRepository.cs
- src/VirtoCommerce.Platform.Data/Infrastructure/DbContextRepositoryBase.cs
- src/VirtoCommerce.Platform.Data/Settings/SettingsManager.cs
- SettingsManager throws an exception when saving object settings only with modified properties
https://virtocommerce.atlassian.net/browse/VCST-1791
Image tag:
ghcr.io/VirtoCommerce/platform:3.851.0-pr-2835-9621-vcps-readonly-settings-96213d2f
> fix: Ignore fixed settings in SaveObjectSettingsAsync()

- src/VirtoCommerce.Platform.Core/Modularity/ModuleCatalog.cs
- src/VirtoCommerce.Platform.Core/Modularity/ModuleDependencySolver.cs
- src/VirtoCommerce.Platform.Core/Modularity/ModuleSequenceBoostOptions.cs
- src/VirtoCommerce.Platform.Modules/External/ExternalModuleCatalog.cs
- src/VirtoCommerce.Platform.Modules/Local/LocalStorageModuleCatalog.cs
- src/VirtoCommerce.Platform.Web/Controllers/Api/ModulesController.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
- tests/VirtoCommerce.Platform.Tests/Modularity/ExternalModuleCatalogTests.cs
- tests/VirtoCommerce.Platform.Tests/Modularity/ModuleInstallerUnitTests.cs
- tests/VirtoCommerce.Platform.Tests/Modularity/ModulePlatformCompatibilityTests.cs
```json
"VirtoCommerce": {
"ModuleSequenceBoost": [
"VirtoCommerce.AuditLog"
],
...
```
https://virtocommerce.atlassian.net/browse/VCST-1736
Image tag:
ghcr.io/VirtoCommerce/platform:3.852.0-pr-2837-30dc-vcst-1736-30dc0480
> VCST-1736: add Module Sequence Boost

- src/VirtoCommerce.Platform.Core/Security/ClaimsPrincipalExtensions.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
feat: Extend ClaimsPrincipalExtensions with GetCurrentUserId and resolving of UserIdClaimTypes based on IdentityOptions settings.
https://virtocommerce.atlassian.net/browse/VCST-2048
Image tag:
ghcr.io/VirtoCommerce/platform:3.861.0-pr-2855-d6b6-vcst-2048-d6b67d91
> VCST-2048: Extend ClaimsPrincipalExtensions with GetUserId and GetUserName

- src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/smartFloat.js
fix: Allow to save empty field for catalog property with type decimal number
https://virtocommerce.atlassian.net/browse/VCST-2213
Image tag:
ghcr.io/VirtoCommerce/platform:3.862.0-pr-2859-a4bf-vcst-2213-a4bfb288
> VCST-2213: Cannot save empty field for catalog  property with type decimal number

- src/VirtoCommerce.Platform.Web/wwwroot/js/common/uiGridUtils.js
Looks like a bug in ui grid. As a workaround I decided to remove empty objects and arrays before state restoring.
https://virtocommerce.atlassian.net/browse/VCST-2300
Image tag:
ghcr.io/VirtoCommerce/platform:3.873.0-pr-2866-2792-vcst-2300-27928233
> VCST-2300: remove empty objects from ui grid state

- src/VirtoCommerce.Platform.Core/Logger/ConsoleLog.cs
- src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs
- src/VirtoCommerce.Platform.Modules/ModuleManager.cs
- src/VirtoCommerce.Platform.Web/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.Platform.Web/Program.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
- src/VirtoCommerce.Platform.Web/appsettings.Development.json
- src/VirtoCommerce.Platform.Web/appsettings.Production.json
1. Updated Loggin for Production mode:
2. Added module initialization and post-initialization logging. Can be enabled by this:
```json
{
"Serilog": {
"MinimumLevel": {
"Override": {
"VirtoCommerce.Platform.Modules": "Debug"
}
}
}
}
```
Without setting:
With setting:
3. Refactored Serilog registration based on<br>
https://github.com/serilog/serilog-aspnetcore?tab=readme-ov-file#two-stage-initialization
https://github.com/serilog/serilog-extensions-hosting?tab=readme-ov-file#instructions<br>
Replaced `ConsoleLog` with static Serilog's `Log.Logger` and `ILogger` injection support.<br>
`ILogger` will not log any messages to Serilog during DI initialization without this changes, because previous implementation registered it at the end of DI registration, after all other services …
> Refactor serilog initialization and add module initialization logging

- src/VirtoCommerce.Platform.Web/Controllers/Api/AuthorizationController.cs
https://virtocommerce.atlassian.net/browse/VCST-2464
Image tag:
ghcr.io/VirtoCommerce/platform:3.875.0-pr-2869-9601-vcst-2464-960195ce
> VCST-2464: Fix refresh token after impersonation

- src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/widget/widgetContainer.tpl.html
fix: Hides widget placeholder if count of widgets is zero
https://virtocommerce.atlassian.net/browse/VCST-2525
Image tag:
ghcr.io/VirtoCommerce/platform:3.875.0-pr-2874-a247-vcst-2525-a247851b
> VCST-2525: Hides widget place holder if count of widgets is zero

- src/VirtoCommerce.Platform.Web/npm-shrinkwrap.json
- src/VirtoCommerce.Platform.Web/package.json
- src/VirtoCommerce.Platform.Web/wwwroot/src/js/vendor.js
fix: Updated npm-shrinkwrap.json to add license info, update dependency versions, and remove unnecessary packages.
fix: Updated package.json to include `jquery-ui` and removed `webpack-jquery-ui`.
https://virtocommerce.atlassian.net/browse/VCST-2471
Image tag:
ghcr.io/VirtoCommerce/platform:3.876.0-pr-2875-d3f0-vcst-2471-d3f08416
> VCST-2471: Update dependencies and replace webpack-jquery-ui

- src/VirtoCommerce.Platform.Web/Middleware/NoCacheForApiMiddleware.cs
- src/VirtoCommerce.Platform.Web/Startup.cs
feat: Introduced NoCacheForApiMiddleware to set HTTP headers (Cache-Control, Pragma, Expires) to prevent caching for API responses if hosting doesn't set it automatically.
https://virtocommerce.atlassian.net/browse/VCST-2599
Image tag:
ghcr.io/VirtoCommerce/platform:3.878.0-pr-2877-b5e4-vcst-2599-b5e47801
> VCST-2599: Add NoCacheForApiMiddleware to prevent API response caching

- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/de.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/es.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/fr.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/it.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ja.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/pl.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/pt.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ru.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/Localizations/zh.VirtoCommerce.Platform.json
- src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_forms.sass
- src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/dynamicProperty-detail.tpl.html
feat: Add language toggle for dynamic property display names.
[VCST-2960]: https://virtocommerce.atlassian.net/browse/VCST-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Image tag:
ghcr.io/VirtoCommerce/platform:3.883.0-pr-2903-d3c8-vcst-2960-d3c82e63
> VCST-2960: Add language toggle for dynamic property display names.

- src/VirtoCommerce.Platform.Web/wwwroot/js/common/uiGridUtils.js
feat: Enable grid header tooltips by default when not explicitly set.
https://virtocommerce.atlassian.net/browse/VCST-2997
Image tag:
ghcr.io/VirtoCommerce/platform:3.884.0-pr-2906-5ba1-vcst-2997-header-tooltip-5ba16a22
> VCST-2997: Enable grid header tooltips by default when not explicitly set

- src/VirtoCommerce.Platform.Web/appsettings.json
https://virtocommerce.atlassian.net/browse/VCST-3370
Image tag:
ghcr.io/VirtoCommerce/platform:3.890.0-pr-2918-469c-vcst-3370-469c8336
> VCST-3370: Set SqlServer.CompatibilityLevel=120 by default

- src/VirtoCommerce.Platform.Core/Modularity/LocalStorageModuleCatalogOptions.cs
fix: Add .zip extension to copy into app_data\modules folder. For example, it allows Azure Monitor access to TraceUpload.zip.
https://virtocommerce.atlassian.net/browse/VCST-3739
Image tag:
ghcr.io/VirtoCommerce/platform:3.902.0-pr-2931-87b0-vcst-3739-87b05e5b
> VCST-3739: Add .zip extension to AssemblyServiceFileExtensions

- src/VirtoCommerce.Platform.Hangfire/VirtoCommerce.Platform.Hangfire.csproj
https://virtocommerce.atlassian.net/browse/VCST-3952
Image tag:
ghcr.io/VirtoCommerce/platform:3.907.0-pr-2940-aeda-vcst-3952-hangfire-update-aeda8908
> VCST-3952: Hangfire version upgrade to 1.8.21
